elastic/elasticsearch-hadoop

- build.gradle
since you use Cascading 2.6.3 as a dependency, it should also point to the correct javadoc.
> Use javadoc of Cascading 2.6

- .travis.yml
- build.gradle
- dist.gradle
The `signing` plugin is enabled when a job is being built from anything other than a `SNAPSHOT` version. Travis CI does not pass when project version does not end in `SNAPSHOT`
> Gradle signing plugin breaks CI workflow

- mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/mapping/Field.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/FieldTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/mapping_with_fields_named_properties_and_type.json
Created method to distinguish between 'properties' ES key (used to define child fields) and user-defined object field named 'properties' when parsing mapping.
Closes [#809](https://github.com/elastic/elasticsearch-hadoop/issues/809)
> Fixed parsing of ES mapping with OBJECT field named 'properties'

- mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/NetworkUtils.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/PartitionDefinition.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SearchRequestBuilder.java
- mr/src/main/java/org/elasticsearch/hadoop/util/StringUtils.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/FindPartitionsTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/PartitionDefinitionTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestServiceTest.java
- spark/core/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDD.scala
In Hadoop and Spark it is possible to set the list of hostnames/ips that should be preferred when a task is launched.
This change restores the heuristic that prefers ES nodes that are local to the task when a partition reader is created.
This means that if an ES node is on the same machine than an Hadoop/Spark worker and this node contains the targeted index/shardId then the PartitionReader will request this node in priority.
Closes #814
> Restores the ability to prefer local nodes when creating a PartitionReader

- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/DelegatedProtocol.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransportTests.java
When SSL is used to communicate with elasticsearch, we replace the Protocol for
`https` with a custom protocol that uses a custom created SSLSocketFactory. The
DelegatedProtocol we create wraps the existing protocol, which is fine if we only
wrap a single time. However if the http transport is instantiated multiple times,
the protocol that is wrapped will be the DelegatedProtocol that we created previously
and this causes the existing SSLSocketFactory to be retained indefinitely.
This change adds a check to see if the existing Protocol is a DelegatedProtocol and
if so the original Protocol is retrieved so that we do not retain a reference to the
DelegatedProtocol and its SSLSocketFactory.
> fix memory leak caused by re-wrapping DelegatedProtocol

- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
Because of type inference, not explicitly providing providing a return type for:
`def buildScan(requiredColumns: Array[String], filters: Array[Filter])`
... gives it the return type `ScalaEsRowRDD` which is a compatible type with the overridden method but limits further overriding on which some transformation is performed by the means of Spark. e.g:
```scala
org.evilcorpt.spark.sql
class SomeNewClass(...) extends ElasticsearchRelation(...) {
...
def buildScan(requiredColumns: Array[String], filters: Array[Filter]): RDD[Row] =
super.buildScan(requiredColumns, filters).map(someTransformationFunction)
...
}
```
> Explicitly specify `buildScan` return type

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
JavaEsSpark failed to initialise when we set discovery to false and throw an NPE
```
new SparkConf()
.setAppName("test").setMaster("local[8]")
.set("es.nodes", "localhost")
.set("es.port", "9200")
.set("es.nodes.discovery","false")
.set("es.nodes.wan.only","true")
```
It was only working with discovery on:
```
new SparkConf()
.setAppName("test").setMaster("local[8]")
.set("es.nodes", "localhost")
.set("es.port", "9200")
.set("es.nodes.discovery","true")
.set("es.nodes.wan.only","false")
```
This PR provides a workaround and populates the `nodes` list with the help of the client instead of discovery if discovery is off.
> Fix NPE when es.nodes.discovery is set to false

- docs/src/reference/asciidoc/core/spark.adoc
In version 5.0.0-alpha5 of the elasticsearch-hadoop connector, we have:
From: org.elasticsearch.spark.sql.java.api.JavaEsSpark SQL  => To: import org.elasticsearch.spark.sql.api.java.JavaEsSparkSQL
> Fix import of JavaEsSparkSQL

- docs/src/reference/asciidoc/core/spark.adoc
pairRDD.saveToEsWithMeta<3>(airportsRDD,"airports/2015") should change to
airportsRDD.saveToEsWithMeta<3>("airports/2015")
and 
pairRDD.saveToEsWithMeta(airportsRDD, "airports/2015") should change to airportsRDD.saveToEsWithMeta("airports/2015")
> spark.adoc have some error

- mr/src/main/java/org/elasticsearch/hadoop/rest/query/QueryUtils.java
As discussed at https://github.com/elastic/elasticsearch-hadoop/pull/864#issuecomment-252745629, to avoid "NullPointerException" if query is not a valid ressource, could help people to understand whats really happened.
> Throw clean exception if query is not well formed

- docs/src/reference/asciidoc/index.adoc
Fixing repo hdfs link for 5.0 as its now in Elasticsearch proper
> Fixing repository-hdfs link

- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
> Fix setup httpProxy property

- cascading/src/itest/java/org/elasticsearch/hadoop/integration/cascading/AbstractCascadingHadoopJsonReadTest.java
- cascading/src/itest/java/org/elasticsearch/hadoop/integration/cascading/AbstractCascadingLocalJsonReadTest.java
- cascading/src/itest/java/org/elasticsearch/hadoop/integration/cascading/CascadingHadoopSuite.java
- cascading/src/itest/java/org/elasticsearch/hadoop/integration/cascading/CascadingLocalSuite.java
- cascading/src/main/java/org/elasticsearch/hadoop/cascading/CascadingValueWriter.java
- cascading/src/main/java/org/elasticsearch/hadoop/cascading/EsHadoopScheme.java
- cascading/src/main/java/org/elasticsearch/hadoop/cascading/EsLocalScheme.java
If `es.output.json` is enabled, instead of deserializing JSON data into a map object ES-Hadoop will simply return the raw JSON string to the user. This is returned from the Hadoop RecordReader as a `Text` object containing the string data. When the Cascading integration receives data from a RecordReader or from a ScrollQuery, it automatically assumes that the data is a Map object. This leads to a cast exception when it receives a Text object instead.
This relates to issue #885.
> Fix `es.output.json` for Cascading.

- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigReadAsJsonTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/PigSuite.java
- pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
If `es.output.json` is enabled, instead of deserializing JSON data into a map object ES-Hadoop will simply return the raw JSON string to the user. This is returned from the Hadoop RecordReader as a `Text` object containing the string data. When the Pig integration receives data from a RecordReader, it automatically assumes that the data is a Map object. This leads to a cast exception.
This bug fell through for a while because the tests surrounding reading JSON data only check to see if the previously inserted raw JSON data can be read back out traditionally. I have added a new test that will make sure that same data can be read back out as raw JSON.
This relates to the issue #871.
> Update to EsStorage to account for JSON output mode

- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveReadJsonTest.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/HiveSuite.java
- hive/src/main/java/org/elasticsearch/hadoop/hive/EsHiveInputFormat.java
- hive/src/main/java/org/elasticsearch/hadoop/hive/EsSerDe.java
- hive/src/main/java/org/elasticsearch/hadoop/hive/HiveUtils.java
If `es.output.json` is enabled, instead of deserializing JSON data into a map object ES-Hadoop will simply return the raw JSON string to the user. This is returned from the Hadoop RecordReader as a `Text` object containing the string data. When the Hive integration receives data from a RecordReader, it automatically assumes that the data is a Map object. This leads to a cast exception when it receives a Text object instead.
In order for Hive to correctly accept the data, it must conform structurally to Hive's table schema. Instead of requiring the user to name their string field a certain way, the code now checks if it is expecting raw JSON data and selects an appropriate schema field from the table definition to place the information into. All other fields will be left as nulls.
This …
> Fix `es.output.json` for Hive

- spark/core/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDD.scala
- spark/core/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDDIterator.scala
- spark/core/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
Fixes #958 
Adds transient annotation to all loggers to avoid serialization issues
- [X ] I have signed the [Contributor License Agreement (CLA)][]
> #958 - added transient to loggers where necessary

- build.gradle
Add Scala compiler options to warn bad code. Compiler output example is:
```
/Users/naoki.takezoe/elasticsearch-hadoop/spark/core/main/scala/org/elasticsearch/spark/rdd/EsSpark.scala:102: discarded non-Unit value
rdd.sparkContext.runJob(rdd, new EsRDDWriter(config.save(), hasMeta).write _)
^
/Users/naoki.takezoe/elasticsearch-hadoop/spark/core/main/scala/org/elasticsearch/spark/rdd/JavaEsRDD.scala:49: discarded non-Unit value
InitializationUtils.setValueReaderIfNotSet(settings, classOf[JdkValueReader], log)
^
/Users/naoki.takezoe/elasticsearch-hadoop/spark/core/main/scala/org/elasticsearch/spark/rdd/ScalaEsRDD.scala:51: discarded non-Unit value
InitializationUtils.setValueReaderIfNotSet(settings, classOf[ScalaValueReader], log)
^ …
```
> Add Scala compiler options

- mr/src/main/java/org/elasticsearch/hadoop/cfg/InternalConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SearchRequestBuilder.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/ValueParsingCallback.java
- mr/src/main/java/org/elasticsearch/hadoop/util/Assert.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/QueryTest.java
- spark/sql-13/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/Utils.java
- spark/sql-20/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/Utils.java
The PR solves `scala.MatchError` in Spark SQL queries with `_metadata` field inside.
More details on the issue: https://github.com/elastic/elasticsearch-hadoop/issues/924
I was trying to update integration tests with that case,
but I am getting failed tests even for the current code in branch `5.1`.
[x] I have signed the [Contributor License Agreement (CLA)][]
> Fix spark sql queries with metadata field

- README.md
- docs/src/reference/asciidoc/core/intro/download.adoc
- docs/src/reference/asciidoc/core/intro/features.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- docs/src/reference/asciidoc/core/mr.adoc
Deprecations for Hadoop 1.x and the old `mapred` api
> Deprecate Hadoop 1.x in 5.5

- README.md
Fixed wrong reference to maven central
> fixed reference to maven dependency

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
`MissingFormatArgumentException` was thrown if the log level is set to `DEBUG`, this PR fixes it.
> Remove unmatched format specifier from Restservice

- docs/src/reference/asciidoc/appendix/breaking.adoc
Hello,
the release ES-Hadoop 5.5 actually breaks the previous backward compatibility with Elasticsearch 2.x as mentioned also in the following [documentation page](https://www.elastic.co/guide/en/elasticsearch/hadoop/5.5/requirements.html#requirements-es)
```We highly recommend using the latest Elasticsearch (currently 5.5.3), but elasticsearch-hadoop is also backwards compatible with the 1.X and 2.X versions of Elasticsearch.```
You only …
> Adding comment on breaking change

- docs/src/reference/asciidoc/index.adoc
Documentation shows 1.6.2 as the latest Spark version but Apache documentation indicates 2.2.0
> Updating Spark latest version

- README.md
It should be `saveToEs` not `saveToES`
> fix misspelling saveToEs function in Spark SQL sections

- docs/src/reference/asciidoc/core/configuration.adoc
- docs/src/reference/asciidoc/core/errorhandlers.adoc
- docs/src/reference/asciidoc/core/index.adoc
Coming soon in 6.2 will be an error handling system. This PR adds documentation for the first set of error handlers, the bulk write error handlers. As we increase the number of error handlers, so too will the documentation evolve to cover them.
> Documentation for error handlers

- docs/src/reference/asciidoc/core/configuration.adoc
- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
For queries that process many indexes with many shards findSlicePartitions is the slowest.
There is a separate indexes for each day, every contains tens millions documents, i need to query six months for example.
findShardPartitions gets a lot more partitions, but it does not delay the execution.
Let, in my case, findShardPartitions will receive 18k partitions, but they will be processed in 10 minutes than I will wait until findSlicePartitions is performed in almost 2 hours.
> Add switchable findPartitions behavior.

- docs/src/reference/asciidoc/core/spark.adoc
When I try to insert JSON that contains breaklines (I was on a Windows env), resulting Mapping does not contains my fields, I only end up with the JSON content in the source field : 
{"_index":"spark","_type":"json-xxx","_id":"myId","_score":1.0,"_source":{"field1" : 1, "field2" : "2"}}
> Update spark.adoc for Windows

- mr/src/main/java/org/elasticsearch/hadoop/rest/ErrorExtractor.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/EsHadoopBulkException.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/EsHadoopRemoteException.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/bulk/BulkProcessor.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/bulk/BulkResponse.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ErrorExtractorTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/bulk/BulkProcessorTest.java
#1115 Added support to bulk error handling to generate exception stack for caused_by trees. Improved reporting of errors in BulkProcessor to include type and stack of messages.
> #1115 Added support to bulk error handling to generate exception stack

- mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
When we debug the mapreduce program, EsInputSplit's detail message will tell us what the map is doing.
> add EsInputSplit.toString method which can be used for debugging

- gradle.properties
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
This just upgrades the scala minor versions to the latest. This is to fix compile issues within java 9/10 environment(s).
> Upgrade Scala minor version to support Java 9/10

- docs/src/reference/asciidoc/core/errorhandlers.adoc
- hive/src/main/java/org/elasticsearch/hadoop/hive/EsSerDe.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/BulkEntryWriter.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/handler/write/SerializationAbortOnFailure.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/handler/write/SerializationDropAndLog.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/handler/write/SerializationErrorHandler.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/handler/write/SerializationFailure.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/handler/write/SerializationHandlerLoader.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/bulk/BulkEntryWriterTest.java
Add error handler API to wrap the execution of serializing records to JSON bulk entries. This should encapsulate the process of extracting document metadata from the record to place in the action header, as well as the traversal and conversion of the record fields to JSON data.
> Add serialization error handler API

- mr/src/main/java/org/elasticsearch/hadoop/rest/SearchRequestBuilder.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/QueryTest.java
val conf = new SparkConf().setAppName("EsTest").setMaster("local[*]")
conf.set("spark.sql.shuffle.partitions", "6")
conf.set("spark.default.parallelism", "6")
conf.set("es.cluster.name", "common")
conf.set("es.nodes", "localhost")
conf.set("es.port", "9200")
val sc = new SparkContext(conf)
val sqlContext = new SQLContext(sc)
val index = "le_plan_d/dpa"
val query = "{\"query\":{\"match_all\":{}}}"
val dataFrame = sqlContext.esDF(index, query)
dataFrame.show(2)
My index has more than 600 fields. I execute a simple match_all query. 
The wrong information is as follows: 
Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: An HTTP line is larger than 4096 bytes.
{"query":{"match_all":{}}}
So，Transfer to post mode.
> An HTTP line is larger than 4096 bytes

- docs/src/reference/asciidoc/core/spark.adoc
Have a page for each Spark integration.
There are a bunch of other things we could probably be doing to make our docs more readable and accessible.
> Breaking up the Spark documentation page into sub pages

- docs/src/reference/asciidoc/core/configuration.adoc
- mr/src/itest/java/org/elasticsearch/hadoop/integration/rest/ssl/SSLTests.java
- mr/src/itest/java/org/elasticsearch/hadoop/rest/pooling/AbstractTransportPoolTest.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/main/java/org/elasticsearch/hadoop/cli/ConsolePrompt.java
- mr/src/main/java/org/elasticsearch/hadoop/cli/Keytool.java
- mr/src/main/java/org/elasticsearch/hadoop/cli/Prompt.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/NetworkClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/TransportFactory.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransportFactory.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/SSLSocketFactory.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/pooling/PooledHttpTransportFactory.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/pooling/TransportPool.java
- mr/src/main/java/org/elasticsearch/hadoop/security/EsHadoopSecurityException.java
- mr/src/main/java/org/elasticsearch/hadoop/security/KeystoreWrapper.java
- mr/src/main/java/org/elasticsearch/hadoop/security/SecureSettings.java
- mr/src/test/java/org/elasticsearch/hadoop/cli/KeytoolTest.java
- mr/src/test/java/org/elasticsearch/hadoop/cli/TestPrompt.java
- mr/src/test/java/org/elasticsearch/hadoop/security/KeystoreWrapperTest.java
ES-Hadoop operates based on the configuration for a given job in Hadoop/Spark. In many cases, users need to provide passwords in these configurations. Since these settings are kept as plain text, providing them in the job configuration can be a potential security hazard. This PR adds support for storing password fields in a keystore file, as well as a tool for generating the keystore file.
> Add ability to specify sensitive settings through a keystore

- mr/src/main/java/org/elasticsearch/hadoop/rest/SearchRequestBuilder.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/SearchRequestBuilderTest.java
Bugfix for: https://github.com/elastic/elasticsearch-hadoop/issues/1160
> Bugfix - return _version field in metadata when requested

- buildSrc/build.gradle
Now that `elasticsearch` has [dropped the `alpha1` qualifier default](https://github.com/elastic/elasticsearch/commit/ca24d9a07edabaafeb0b04d94bdff49bb5d975ee) we can as well.
> Remove the alpha1 default build qualifier

- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/MetadataExtractor.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/PerEntityPoolingMetadataExtractor.java
- spark/core/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
- spark/core/main/scala/org/elasticsearch/spark/serialization/ScalaMetadataExtractor.scala
Changes:
* Add support for a user defined MetadataExtractor within Spark. Also includes support for SettingsAware MetadataExtractor classes. 
* Expands the MetadataExtractor interface to recieve the Metadata Object during their work flow. 
* PerEntityPoolingMetadataExtractor expanded to support it's reuse within user defined MetadataExtractors.
[Contributor License Agreement (CLA)]: …
> Support for custom MetadataExtractor within Spark flows

- README.md
- buildSrc/esh-version.properties
- docs/src/reference/asciidoc/index.adoc
This commit bumps the 6.x branch to 6.7.0 now that the 6.6 branch is cut from 6.x.
> Bump the 6.x branch to 6.7.0

- mr/src/test/java/org/elasticsearch/hadoop/serialization/field/DateIndexFormatterTest.java
- pig/src/test/java/org/elasticsearch/hadoop/pig/DateIndexFormatterTest.java
Now pulling the code and doing `./gradlew test` fails `DateIndexFormatterTest`:
```
org.elasticsearch.hadoop.serialization.field.DateIndexFormatterTest > testTimeYMDFormat FAILED
java.lang.AssertionError at DateIndexFormatterTest.java:34
1348 tests completed, 1 failed, 470 skipped
```
It is due to timezone difference. I think it is better to make the test passed no matter timezone.
> Fix DateIndexFormatterTest

- qa/build.gradle
- qa/kerberos/build.gradle
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/ExtendedClient.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/cascading/LoadToES.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/cascading/ReadFromES.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/setup/SetupKerberosUsers.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/CapturingBolt.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/StreamFromEs.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/StreamToEs.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/TestSpout.java
When building release candidates, ES-Hadoop receives its build tools dependency via the release automation so that it has the exact version of the artifact that will be released. This means that any testing code that relies on Elasticsearch versions that are yet to be released needs to be skipped in the release candidate generation as it is both non-production testing code and stuck in a chicken-egg dependency conundrum.
With the addition of the qa kerberos project, this problem becomes a little more difficult, as elasticsearch cluster fixture plugins are not applied when running with a local repository of dependencies. Additionally, the qa-kerberos project depends on integration test code for building artifacts that as previously mentioned is not able to compile due to issues with …
> Disable testing in kerberos project when localRepo is set

- qa/kerberos/build.gradle
The cluster settings for configuring realms changed in 7.0 and were not updated in the 6.7 backport for the kerberos features. This PR fixes the realm settings for the test cluster to get it running again.
> Fix es cluster fixture settings on 6.7

- qa/kerberos/src/itest/java/org/elasticsearch/hadoop/qa/kerberos/AbstractClusterVerificationTests.java
Updates the `AbstractClusterVerificationTests` to be sensitive to the fact that there may be multiple files that contain output from the test jobs in the qa kerberos project.
> Update kerberos file test to account for multiple output files

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
Spark 2.3.2 has been removed from the Apache download mirrors. 
Bump the fixture version up to 2.3.3.
> Update the Spark fixture version to be 2.3.3 by default

- mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/FindPartitionsTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/QueryTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ResourceTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/CommandTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/field/JsonFieldExtractorsTest.java
With the addition of the 8.x version, there have been some tests that needed updating (but weren't failing because of previous problems with the build) for the new version id. This adds the 8.x major version id and updates the tests suites that depend on those versions.
> Fix Unit Test Suites for 8.0

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
Set the `isRuntimeJavaHomeSet` property to false in order to force the cluster formation tasks to always use the bundled JDK version instead of the runtime version on newer versions of ES if it is available.
> Update ES fixtures to always use bundled JDKs if available

- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveExtraTests.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveReadJsonTest.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveSaveJsonTest.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveSaveTest.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveSearchJsonTest.java
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveSearchTest.java
- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractExtraMRTests.java
- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMRNewApiSaveTest.java
- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMRNewApiSearchTest.java
- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMROldApiSaveTest.java
- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMROldApiSearchTest.java
- mr/src/test/java/org/elasticsearch/hadoop/util/TestUtils.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigExtraTests.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigReadAsJsonTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigSaveJsonTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigSaveTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigSearchJsonTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigSearchTest.java
- spark/core/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkTest.java
- spark/core/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- spark/sql-13/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
- spark/sql-13/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkStreamingTest.java
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsScalaSparkStreaming.scala
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
- spark/sql-20/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkStreamingTest.java
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractJavaEsSparkStructuredStreamingTest.java
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsScalaSparkStreaming.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
In the 7.0 line there are changes to ensure that 7.0 respects the deprecation of the usage of Elasticsearch types in requests. This change ensures that the existing test code that depends on typeless API's continues to function in a manner that is backwards compatible with older versions for testing purposes.
The plan at the moment is to remove the types completely in the 8.0 line with a later PR. The backwards compatibility sensitive changes are in this PR for the benefit of running 7.x tests against 6.x clusters.
> Fix the integration test suites usage of typeless api calls

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/IntegrationBuildPlugin.groovy
- hive/build.gradle
- pig/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- storm/build.gradle
When creating the jar files for ES-Hadoop, each integration copies the contents of the MR jar into itself since the MR jar contains all the core code. Once each jar is built, they all contribute their contents to the top level elasticsearch-hadoop jar (ignoring duplicate code files). A problem occurs during these jar transitions: The contents of META-INF/services are not copied along. This previously would manifest as not being able to create a Spark SQL dataframe using the short name `"es"` when using the `elasticsearch-hadoop-x.x.x.jar`. Creating the dataframe using the short name would work fine when using the `elasticsearch-spark-yy_zz-x.x.x.jar` because it contains the appropriate service file, which is never copied up to the root jar.
Now that we have Kerberos integrated, there are …
> Fix missing service files in ES-Hadoop jars

- docs/src/reference/asciidoc/core/hive.adoc
- docs/src/reference/asciidoc/core/intro/download.adoc
- docs/src/reference/asciidoc/core/pig.adoc
- docs/src/reference/asciidoc/core/spark.adoc
- docs/src/reference/asciidoc/core/storm.adoc
Drops the inline callouts from the docs. This is when you write `<1>`
anywhere but the end of a line. Asciidoctor doesn't support them and
we'd very much like to move to Asciidoctor to generate the docs because
it is being actively maintained.
I've taken a shot at removing all of the callouts and everything
compiles but I suspect it doesn't look quite right.
Closes #1262
> Docs: Drop inline callouts

- docs/src/reference/asciidoc/appendix/breaking.adoc
This PR adds a tagged region in the Elasticsearch Hadoop Breaking changes page (https://www.elastic.co/guide/en/elasticsearch/hadoop/master/breaking-changes.html), such that content can be re-used in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html).
At least one tagged region must exist to prevent build errors in the Installation and Upgrade Guide, though as is the case now for V8.0.0 it can be an empty tagged region.
At this time, the Installation and Upgrade Guide for version X only lists the breaking changes specific to that version. Since this Elasticsearch Hadoop page contains information about multiple versions, I've made the tagged regions version-specific (i.e. tag::notable-v8-breaking-changes[]). …
> [DOCS] Adds tagged region for notable breaking changes

- docs/src/reference/asciidoc/core/configuration.adoc
- docs/src/reference/asciidoc/core/pig.adoc
- docs/src/reference/asciidoc/core/spark.adoc
This makes three changes in preparation for switching the docs to
Asciidoctor:
1. Fixes a broken link. As a side effect this fixes a missing emphasis
in Asciidoctor that was caused by parsing issues with the `_` in the old
link.
2. Fixes an `added` macro that renders "funny" in Asciidoctor.
3. Replace a tab in a code example with spaces. AsciiDoc was doing this
automatically but Asciidoctor preserves the tab. We don't need the tab.
> Docs: Clean up for asciidoctor

- docs/src/reference/asciidoc/index.adoc
This PR adds the use of the shared attributes file: https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc
... and removes redundant definitions from https://github.com/elastic/elasticsearch-hadoop/blob/master/docs/src/reference/asciidoc/index.adoc
If there are any other attributes that are used in the Breaking changes (https://www.elastic.co/guide/en/elasticsearch/hadoop/master/breaking-changes.html), they must also be added to the shared attributes file.  Otherwise, they will not work when the content is pulled into the Installation and Upgrade Guide
(https://www.elastic.co/guide/en/elastic-stack/master/elasticsearch-hadoop-breaking-changes.html)
> [DOCS] Adds shared attributes

- buildSrc/build.gradle
- buildSrc/esh-version.properties
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/EshVersionProperties.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/RootBuildPlugin.groovy
Elasticsearch has upgraded the minimum required version of Java to be 11. ES-Hadoop's build setup still relies on Java 8. In order to get the build running on Java 11, Gradle would need to be upgraded to version 5.0, which currently breaks the Scala cross compilation set up in the Spark projects.
In order to get snapshot builds running again, this PR changes the build-tools artifact to an older version that still supports Java 8. Once the build versions have been updated, we can restore the build tools dependency to how it was before.
> Revert build-tools to older version

- docs/src/reference/asciidoc/index.adoc
This PR updates the version attributes (https://github.com/elastic/docs/blob/master/shared/versions71.asciidoc) that are used by the 7.1 branch of the Elasticsearch for Apache Hadoop book.
> [DOCS] Updates version attributes

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- mr/src/test/java/org/elasticsearch/hadoop/util/EsMajorVersionTest.java
Master branch has been failing for a while now since the ES project bumped its required Java version to 11. ES-Hadoop is still on Java 8, and will need extra testing before compiling and running tests on Java 11. Until then, this PR replaces the version test with cases that do not depend on the versions contained within the Elasticsearch project. When ES-Hadoop is ready to bump up to a higher java version, the version parsing tests can be returned to their original functionality.
> Fix master compilation from ES on Java 11

- .travis.yml
Travis CI task is failing due to not being able to install/use Java 8. This PR resets the ubuntu distribution to Trusty in order to pick up the older version of Java.
> Set ubuntu dist to trusty

- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/AbstractHiveSaveTest.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ResourceTest.java
- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigSaveTest.java
- spark/core/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
This PR removes the include_type_names parameter from mapping requests made to versions of ES that do not recognize it. Included are a set of test updates that ensures that test runs against ES 5.x complete correctly.
Relates #1276
> Fix the mapping client call on ES 5.x and earlier.

- docs/src/reference/asciidoc/index.adoc
This PR updates the Elasticsearch for Apache Hadoop and Spark book to use appropriate version information from https://github.com/elastic/docs/blob/master/shared/versions73.asciidoc
> [DOCS] Updates version attribute file

- docs/src/reference/asciidoc/index.adoc
Related to https://github.com/elastic/docs/issues/930
This PR updates the documentation version attributes from 6.8.0 to 6.8.1
> [DOCS] Updates documentation version

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
- [ X ] I have signed the [Contributor License Agreement (CLA)][]
Hi
A simple bug fix to make the library still working with older ES versions that do not provide cluster UUID info
Replaces #1299
> Fix NPE with old ES version

- spark/sql-13/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
Assert `results` variable instead of `dataFrame`
> Small test fix

- docs/src/reference/asciidoc/core/configuration.adoc
- docs/src/reference/asciidoc/core/spark.adoc
elastic/elasticsearch/pull/44238 moved several Elasticsearch APIs to a REST APIs section.
As a result of that move, some pages were converted to anchored sections. This will fix links to those pages once the above PR is re-applied.
I plan to merge this PR simultaneously with:
- elastic/elasticsearch/pull/44238
- elastic/elasticsearch/pull/44279
- elastic/kibana/pull/41001
- elastic/stack-docs/pull/411
> [DOCS] Fix broken links for ES API docs move

- buildSrc/esh-version.properties
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
Lucene's snapshot version was wrong which resulted in failed builds.
1. ES version was used instead of Lucene version in the BuildPlugin`
2. Lucene's snapshot version was wrong in the properties file
> Fix Lucene's snapshot version

- docs/src/reference/asciidoc/core/configuration.adoc
- docs/src/reference/asciidoc/core/spark.adoc
elastic/elasticsearch#44372 moved the navigation for several Elasticsearch APIs under the [REST APIs section](https://www.elastic.co/guide/en/elasticsearch/reference/master/rest-apis.html). That PR included [several redirects](https://github.com/elastic/elasticsearch/pull/44372/files#diff-427622c7e85f29d0b8f204c583e153f1) to avoid broken links.
This PR updates links pointing to those redirected anchors and links. This saves users a step when visiting these links.
[skip ci]
> [DOCS] Update anchors and links for Elasticserach API relocation.

- buildSrc/build.gradle
- buildSrc/esh-version.properties
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/EshVersionProperties.groovy
Part of 7.x build-tools now have Java 8 support, so VersionProperties
can be used to retrieve Lucene's snapshot version and therefore there is
no need to set it manually to the properties file.
Fixes: #1321
> Use new snapshot of build-tools with Java 8 support

- docs/src/reference/asciidoc/index.adoc
Increments the documentation attribute for the 7.2.1 release.
Will merge on release day.
> [DOCS] Bump docs version from 7.2.0 to 7.2.1

- README.md
- buildSrc/esh-version.properties
- docs/src/reference/asciidoc/index.adoc
Prepping for version bump.
Do not merge until green light given to bump versions (CI failures are expected)
> Bump version to 7.3.1

- mr/src/itest/java/org/elasticsearch/hadoop/LocalEs.java
This is no longer need, because 1 shard is the default since 7.0
> Remove LocalEs#setSingleNodeTemplate() method

- mr/src/main/java/org/elasticsearch/hadoop/rest/NetworkClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/NetworkClientTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
Scroll requests cannot be retried on other nodes.
This can lead to less document being returned than is expected or
ES returning an error because a scroll id is accessed multiple times.
Closes #1302
> Do not retry scroll requests in NetworkClient.

- docs/src/reference/asciidoc/core/configuration.adoc
The anchor is specified explicitly in the reformatted API ref.
> [DOCS] Fixing a cross doc link to a generated anchor.

- docs/src/reference/asciidoc/index.adoc
Increments the documentation attribute for the 7.3.1 release.
**DO NOT MERGE UNTIL RELEASE DAY**
> [DOCS] Bump docs version to 7.3.1

- buildSrc/build.gradle
- buildSrc/esh-version.properties
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
As of https://github.com/elastic/elasticsearch/pull/45677 build tools 
now uses a function that requires javaHome to be a `File` type.
This commit updates the JavaHome property to be a File type. This
commit also bumps the latest supported version of build-tools (8.0.0-SNAPSHOT
is not supported yet).
> use File type for javaHome and bump build-tools version

- docs/src/reference/asciidoc/index.adoc
Related to elastic/docs#1109 and elastic/docs#1108
This PR updates the Elasticsearch for Hadoop book (https://www.elastic.co/guide/en/elasticsearch/hadoop/current/index.html) in the 7.x branch to use the appropriate shared version attributes file.
> [DOCS] Updates version attributes filename

- docs/src/reference/asciidoc/index.adoc
Related to elastic/docs#804
Depends on elastic/docs#1148 and elastic/docs#1147
This PR changes the location of the shared version attributes (so that updates are not required every time there's a new branch).
> [DOCS] Updates location of version attribute for Apache Hadoop Guide

- docs/src/reference/asciidoc/core/intro/download.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- docs/src/reference/asciidoc/index.adoc
- Replaces the `{vers}` attribute with the `{version}` attribute from the [stack version file](https://raw.githubusercontent.com/elastic/docs/master/shared/versions/stack/master.asciidoc).
- Replaces the `{es-vers}` attribute with the `{elasticsearch_version}` attribute from the [stack version file](https://raw.githubusercontent.com/elastic/docs/master/shared/versions/stack/master.asciidoc).
- Update the `ver-d` attribute value
> [DOCS] Use shared attributes

- pig/src/itest/java/org/elasticsearch/hadoop/integration/pig/AbstractPigReadAsJsonTest.java
In the master branch, Elasticsearch no longer returns the type metadata as part of a search operation. The Pig tests expect this data to be present and are thus failing. This PR fixes the logic in the pig tests to check the version before expecting the type to be present in metadata.
> Fix pig test failures

- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Recently the `_source` endpoints have had their types removed. There are a few spots in the test code that uses these end points that really don't need to be using them in the first place. This PR removes them to get the tests passing again.
> Fix spark test failures

- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
This commit introduces a 3rd party plugin to co-locate
scala docs with java docs. https://github.com/lightbend/genjavadoc
Fixes: #1363
> Add scala docs to javadocs

- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- Add scala docs to javadocs (#1368)
> [7.x] Add scala docs to javadocs (#1368)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/InstanceInfo.groovy
This commit adapts the elasticsearch-hadoop build to an upstream change to make some build globals type safe. In particular, we adapt the usage of Java versions.
Relates elastic/elasticsearch#48778
> Adapt to upstream for type safe build globals

- docs/src/reference/asciidoc/core/configuration.adoc
This setting is often misunderstood and misused, especially when it comes to nested fields. This PR updates the docs in an attempt to better explain the usage of the field with more information in the examples.
> Update text around es.read.field.as.array.include

- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
#1368 introduces a plugin that is documents scala apis
for java developers. This plugin does not support 2.10 and
this variant was missed in the initial testing.
This commit for 7.x conditionally uses this plugin based on the
scala major version. 2.10 support has been removed for 8.x.
> Do not build scala docs as javadocs for scala 2.10

- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-beta1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.1.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.1.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.2.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.2.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.4.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.5.0.adoc
Removes release dates from Elasticsearch Hadoop release notes for the master branch.
Relates to #1329 
Will open separate PRs for the 7.x->7.0 and 6.x->6.0 branches.
> [DOCS] Remove release dates from release notes

- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-beta1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.0.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.1.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.1.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.2.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.2.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.3.2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.4.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.4.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.4.2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.5.0.adoc
Removes release dates from Elasticsearch Hadoop release notes for the 7.x branch.
Backport of #1396. I plan to backport this to 7.5.
Relates to #1393 and #1396
> [DOCS] [7.x] Remove release dates from release notes

- docs/src/reference/asciidoc/page_header.html
Explicitly set page_header.html for 6.8 so that the default notice can be updated for OOM versions.
Prerequisite for: https://github.com/elastic/docs/pull/1528
> [DOCS] Added older release notice.

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
Gradle 6 has some additional restrictions where it will not resolve artifacts unless they have metadata available, or unless the repository is set to directly retrieve them.
This also removes some left over code from a previous issue.
> Fix failures due to changes in Gradle 6 artifact resolution

- docs/src/reference/asciidoc/core/configuration.adoc
This float tag is broken and docbook has been ignoring it.
`--direct_html` doesn't ignore it though.
> Docs: Remove a broken [float]

- spark/core/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
The index template body has changed on master and thus one of our tests that uses it is failing. This PR fixes the test in a backwards compatibility supporting manner.
fixes #1417
> Fix master test failures

- buildSrc/esh-version.properties
Note: I did not update the README since it already points to 7.6.0 for the stable release, which I believe is correct?
> Bump version to 7.6.1

- README.md
Noticed the master README was still pointing at `7.4.1`, updates to `7.6.0`
> Update README to point to 7.6.0

- docs/src/reference/asciidoc/core/configuration.adoc
- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
The default scroll size we use for reading data from Elasticsearch is currently set to 50. We feel like this number is much too low for a default value. This PR increases the default scroll size from 50 documents to 1000 documents, parallel to the default scroll size used in Elasticsearch's reindex api.
This change is marked as breaking since it changes a default configuration value which may affect existing low memory Hadoop deployments that do not set this property.
> Boost default scroll size to 1000

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/IntegrationBuildPlugin.groovy
- hive/build.gradle
- mr/build.gradle
- pig/build.gradle
- qa/kerberos/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- storm/build.gradle
- test/fixtures/minikdc/build.gradle
The original Gradle configuration names of `compile` and `runtime` are deprecated. This PR replaces their uses in the build with new/current configurations. 
Specifically, this PR converts uses of the `compile`  configuration to instead use the `implementation` or `api` configurations. It also swaps the use of the `runtime` configuration over to use `runtimeClasspath`.
Did some light tidying up as well.
> Remove deprecated Gradle configurations

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/ConfigFormats.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopClusterFormationTasks.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/InstanceInfo.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/ServiceDescriptor.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/EndProcessConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/HadoopClusterConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/ProcessConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/SettingsContainer.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HadoopServiceDescriptor.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HiveServiceDescriptor.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/PigServiceDescriptor.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/AbstractClusterTask.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/DfsCopy.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/PigScript.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/ObjectUtil.groovy
- qa/kerberos/build.gradle
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/setup/SetupKerberosUsers.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/StreamFromEs.java
- qa/kerberos/src/main/java/org/elasticsearch/hadoop/qa/kerberos/storm/StreamToEs.java
- qa/kerberos/src/main/resources/hive/load_to_es.sql
- qa/kerberos/src/main/resources/hive/read_from_es.sql
- qa/kerberos/src/main/resources/pig/load_to_es.pig
- qa/kerberos/src/main/resources/pig/read_from_es.pig
- test/fixtures/minikdc/build.gradle
This PR includes changes necessary to run the Kerberos QA tests using the new test clusters functionality in build-tools. 
This also updates the project to run fixtures on the Java 8 runtime. JAVA_HOME can now be set on cluster configs and is used by fixtures.
A cluster can be configured with a dependent ElasticsearchCluster. This cluster is depended on for any configuration tasks in case its cluster address is used.
Settings are now stored as objects in cluster configurations instead of Strings since they may be GStrings with closures inside of them that must be resolved ONLY at configuration writing time. This is needed to resolve test cluster http addresses which are only discoverable once the cluster is started.
In order to make this resolution process simpler, removed most of the …
> Update the QA project to use test cluster api

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- hive/build.gradle
- mr/build.gradle
- mr/src/itest/java/org/elasticsearch/hadoop/Provisioner.java
- pig/build.gradle
- qa/kerberos/build.gradle
- spark/core/itest/java/org/elasticsearch/spark/integration/SparkUtils.java
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- storm/build.gradle
ES-Hadoop currently relies on its integration test code to be jar'd up before the tests are executed since many of the integrations rely on a jar being provided in order to run test code. We have a decent amount of shared code in the integration test projects, so we package it all up into one big jar on the root project, which makes configuring tests very confusing.
This PR removes that root testing jar and instead builds an itest jar in each project that needs it. We still have an issue with the shared code between integration tests, but there will be a follow up PR to address that.
> Remove root project testing jar

- mr/src/main/java/org/elasticsearch/hadoop/serialization/json/BlockAwareJsonParser.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/json/BlockAwareJsonParserTest.java
The BlockAwareJsonParser is used to set a checkpoint on a JSON stream
and exit the current blocks that the cursor is in back to the same
level of the content that it was created at. If skipChildren is called
to skip over an open array or object, the internal level counter will
not be updated to account for the array or object that was skipped over.
This PR updates the skipChildren method to check the currentToken and
conditionally decrement the internal nested level counter if we ended
up at an end of an array or object.
> Fix BlockAwareJsonParser level accounting

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- mr/src/itest/java/org/elasticsearch/hadoop/ProvisionerTest.java
- spark/core/itest/java/org/elasticsearch/spark/integration/SparkUtils.java
- test/shared/src/main/java/org/elasticsearch/hadoop/Provisioner.java
This PR explicitly passes the location of the integration test jars to the integration test task instead of relying on the correct files existing in a relative path from the test's working directory.
> Pass itest jar path to tests through system property

- hive/build.gradle
- pig/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- storm/build.gradle
Use a configuration to embed the contents of the `mr` project into dependent
projects' artifacts instead of using the `mr` project's jar task directly.
Consolidate all projects' dependency blocks into one block for each project.
> Fix project artifact sharing.

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
This PR updates the project build plugin to use BuildParams instead of the now removed GenerateGlobalBuildInfoTask.
> Fix usage of the GlobalBuildInfoPlugin

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- hive/build.gradle
- pig/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- storm/build.gradle
We embed project code from the MR project into each and every integration Project in ES-Hadoop. When generating javadocs, we directly reference the mr project's source sets to pull their contents into the javadoc tool as an input. 
This becomes a problem when a downstream project depends on java source code that is generated by a task. A specific instance of this problem arises when splitting the Spark core and SQL projects apart. The Spark projects take advantage of a compiler plugin to generate java sources specifically to be used with the Javadoc tool. These generated sources must be transmitted from the Spark core projects to the Spark SQL projects so that they may be bundled together in the same documentation package.
This PR adds configurations for importing and exporting source …
> Import sources for javadoc through a dependency

- mr/src/main/java/org/elasticsearch/hadoop/rest/PartitionDefinition.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/FindPartitionsTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/PartitionDefinitionTest.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestServiceTest.java
In situations where large pushdown queries, large mappings, and indices with many shards are combined, we can inflate the driver program memory very quickly as we duplicate the settings and mappings data for each ParititionDefinition we create. This change serializes the settings and mapping data once and shares the immutable state between all PartitionDefinition instances to avoid ballooning memory.
Closes #1476
> Share serialized settings and mappings between partition definitions

- .ci/java-versions.properties
This PR adds a configuration file that the CI system will pick up to determine which version of Java is expected for running tests and builds for the current branch. This will backported to all active development branches.
> Add java-versions.properties file for CI

- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
Setting the java home property was only done on the regular Scala compile task. It should be set on all Scala compile tasks instead.
> Fix Scala test compile Java home usage

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- mr/build.gradle
Remove our git revision parsing code and replace it with the parsing logic from build tools since that handles git worktrees correctly.
> Use build tools to read git revision

- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
This PR moves the dependency report generation logic to the dist subproject, and makes some changes to get the project wide dependency report to generate correctly.
> Move dependency report logic to the dist project

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
The developers tag was removed from the pom file of all artifacts, but is required for release on nexus. Re-add the tag back in but with generic developer content.
> Return developers tag to pom generation

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
Backports the following commits to 7.9:
- Return developers tag to pom generation (#1499)
> [7.9] Return developers tag to pom generation (#1499)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- Return developers tag to pom generation (#1499)
> [7.x] Return developers tag to pom generation (#1499)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/ElasticsearchFixturePlugin.groovy
Some of our rest testing tasks were renamed as part of the refactoring done in https://github.com/elastic/elasticsearch/pull/60261. This broke the hadoop build as it still contains references to those old tasks. Right now this is only failing in our release builds due to the new `build-tools` jar not being published yet but we need to get those builds green to get the updated artifact published.
> Update references to renamed Gradle task

- docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.9:
- [DOCS] Add 7.9.1 release notes (#1518)
> [7.9] [DOCS] Add 7.9.1 release notes (#1518)

- gradle/wrapper/gradle-wrapper.properties
This PR upgrades our version of Gradle to 6.6.
> Upgrade Gradle to version 6.6

- gradle/wrapper/gradle-wrapper.properties
- Upgrade Gradle to version 6.6 (#1537)
> [7.x] Upgrade Gradle to version 6.6 (#1537)

- docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.9:
- [DOCS] Add 7.9.3 release notes (#1545)
> [7.9] [DOCS] Add 7.9.3 release notes (#1545)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/ElasticsearchFixturePlugin.groovy
When running the hadoop build with `-PlocalRepo` as we do for release builds, it seems the integration test cluster tests are configured a bit differently. We are trying to call `systemProperty()` on a task _collection_ which of course won't work. I'm not sure how this ever worked or when this issue was introduced but in any case this sorts the problem out by just nesting the configuration in a call to `.all()`.
The issue was initially discovered in `7.x`, thus this PR but looking it seems the same problem exists in `master` so we'll likely need to port this there as well.
> Fix attempt to apply property to task collection

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
This pull request updates some references to refactored tasks in build-tools. Ironically, the cause here is that we are undergoing an effort in Elasticsearch to make better separation between "internal" and "external" build logic, specifically to minimize fallout to external users, such as es-hadoop. The root cause PR is https://github.com/elastic/elasticsearch/pull/65102.
@jbaiera essentially the new contract is that if you use stuff in an `internal` package we make no breaking changes guarantees. The preferred approach here would be to remove to dependencies on anything `internal` in build-tools. In fact, we eventually intend to remove that stuff entirely and simply not include them in the published build-tools jar.
> Update references to internal precommit plugins

- docs/src/reference/asciidoc/core/metrics.adoc
- docs/src/reference/asciidoc/index.adoc
Backports the following commits to 7.10:
- [DOCS] Fix links to Hadoop docs (#1564)
> [7.10] [DOCS] Fix links to Hadoop docs (#1564)

- docs/src/reference/asciidoc/core/metrics.adoc
- docs/src/reference/asciidoc/index.adoc
- [DOCS] Fix links to Hadoop docs (#1564)
> [7.x] [DOCS] Fix links to Hadoop docs (#1564)

- docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.10.2 release notes (#1568)
> [7.x] [DOCS] Add 7.10.2 release notes (#1568)

- docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.11:
- [DOCS] Add 7.10.2 release notes (#1568)
> [7.11] [DOCS] Add 7.10.2 release notes (#1568)

- docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.11.0 release notes (#1569)
> [7.x] [DOCS] Add 7.11.0 release notes (#1569)

- docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
- [DOCS] Remove 7.10.2 coming tag (#1573)
> [master] [DOCS] Remove 7.10.2 coming tag (#1573)

- docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
- [DOCS] Remove 7.10.2 coming tag (#1573)
> [7.x] [DOCS] Remove 7.10.2 coming tag (#1573)

- docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
Backports the following commits to 7.11:
- [DOCS] Remove 7.10.2 coming tag (#1573)
> [7.11] [DOCS] Remove 7.10.2 coming tag (#1573)

- README.md
- buildSrc/esh-version.properties
This makes the version bump to 7.10.3 as 7.10.2 was released just yesterday. Sorry for the delay
> Version bump to 7.10.3

- gradle.properties
CI is failing at the moment because it cannot locate java installations with the GlobalBuildInfoPlugin.
> Add properties for pulling java versions from the environment variables

- gradle.properties
- Add properties for pulling java versions from the environment variables (#1584)
> [7.x] Add properties for pulling java versions from the environment variables (#1584)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
- spark/core/build.gradle
The new tooling for building Spark/Scala variants seems to have an issue with the core Spark project. This project contains multiple versions of Scala _and_ Spark. The artifacts produced from here are differentiated in name only by the version of Scala. This means that building for Spark 2.0 on 2.11 and Spark 1.6 on 2.11 would produce the same artifact name. Luckily, the core code does not change between these versions and no compatibility issues have yet been raised because of this bug.
This PR updates the Spark integration's core project to prepend the Spark version of its variant to the artifacts classifier as it normally would (we strip this out in the plugin code since the classifier is unneeded for the final products).
> Distinguish core Spark artifacts from each other

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
- spark/core/build.gradle
- Distinguish core Spark artifacts from each other (#1586)
> [7.x] Distinguish core Spark artifacts from each other (#1586)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
- spark/core/build.gradle
Backports the following commits to 7.11:
- Distinguish core Spark artifacts from each other (#1586)
> [7.11] Distinguish core Spark artifacts from each other (#1586)

- docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
- [DOCS] Remove 7.11.0 coming tag (#1579)
> [master] [DOCS] Remove 7.11.0 coming tag (#1579)

- docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
- [DOCS] Remove 7.11.0 coming tag (#1579)
> [7.x] [DOCS] Remove 7.11.0 coming tag (#1579)

- docs/src/reference/asciidoc/appendix/release-notes/7.11.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.11.1 release notes (#1602)
> [7.x] [DOCS] Add 7.11.1 release notes (#1602)

- mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java
Should adress https://github.com/elastic/elasticsearch-hadoop/issues/1612
I am just proposing this PR, but feel free to trash it and be more explicit (introduce a list of valid `data` roles).
It's missing unit tests.
> New Data Tiers role support

- docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.12:
- [DOCS] Add 7.11.2 release notes (#1611)
> [7.12] [DOCS] Add 7.11.2 release notes (#1611)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.12.0 release notes (#1610)
> [7.x] [DOCS] Add 7.12.0 release notes (#1610)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
- [DOCS] Remove 7.12.0 coming tag (#1627)
> [master] [DOCS] Remove 7.12.0 coming tag (#1627)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
- [DOCS] Remove 7.12.0 coming tag (#1627)
> [7.x] [DOCS] Remove 7.12.0 coming tag (#1627)

- docs/src/reference/asciidoc/appendix/breaking.adoc
This PR adds a sentence to the breaking changes, such that it's clear there are no breaking changes in the current release. This information can then be pulled into the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/7.12/elasticsearch-hadoop-breaking-changes.html).
> [DOCS] Update breaking changes

- docs/src/reference/asciidoc/core/intro/download.adoc
Update the spark installation guide to list the new Spark 3.x version line and what items it is compatible with.
> Update Spark installation guide for 3.0

- docs/src/reference/asciidoc/core/intro/download.adoc
- Update Spark installation guide for 3.0 (#1638)
> [7.x] Update Spark installation guide for 3.0 (#1638)

- docs/src/reference/asciidoc/core/intro/download.adoc
- Update Spark installation guide for 3.0 (#1638)
> [master] Update Spark installation guide for 3.0 (#1638)

- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/RootBuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
- gradle.properties
This PR is fixing a few gradle deprecation warnings as preparation for migrating the build to Gradle 7.0.
We plan to migrate the elasticsearch build to Gradle 7.0 as soon as it is released and to keep elasticsearch-hadoop close 
we have to ensure this project works well with Gradle 7.0.
- [ X] I have signed the [Contributor License Agreement (CLA)][]
> Fix Gradle deprecation warnings

- buildSrc/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- qa/build.gradle
This updates this build to use Gradle 7.0 and stay compliant with the latest build-tool changes done to make build tools 7.0 compliant. This PR will pass as soon as https://github.com/elastic/elasticsearch/pull/68506 is merged into master as Gradle 7.0 introduced a breaking change on Gradle JVM resolve logic used by the `GlobalBuildInfoPlugin`.
- [x ] I have signed the [Contributor License Agreement (CLA)][]
> Update Gradle wrapper to 7.0

- build.gradle
Gradle 7.0 changed the default duplicates Strategy to error when duplicates for
a copy or archive operations are detected. This leads to the build to fail
as the elasticsearch hadoop project relied on ignoring duplicates. With this change
we set the duplicatesStrategy for every related task to EXCLUDE
This unblocks the unified release process that currently fails with an error caused by 
duplicates entries for javadocJar.
- [X ] I have signed the [Contributor License Agreement (CLA)][]
> Set explicit duplicatesStrategy for all Copy and Archive Gradle tasks

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/ElasticsearchFixturePlugin.groovy
This PR changes the test fixture plugin to use the new `node.roles` setting instead of `node.ingest`
> Fix the build's usage of the node roles settings

- docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.12.1 release notes (#1645)
> [7.x] [DOCS] Add 7.12.1 release notes (#1645)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
- [DOCS] Remove 7.12.1 coming tag (#1648)
> [7.x] [DOCS] Remove 7.12.1 coming tag (#1648)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
Backports the following commits to 7.13:
- [DOCS] Remove 7.12.1 coming tag (#1648)
> [7.13] [DOCS] Remove 7.12.1 coming tag (#1648)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.13.0 release notes (#1662)
> [7.x] [DOCS] Add 7.13.0 release notes (#1662)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
- [DOCS] Remove 7.13.0 coming tag (#1668)
> [master] [DOCS] Remove 7.13.0 coming tag (#1668)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
- [DOCS] Remove 7.13.0 coming tag (#1668)
> [7.x] [DOCS] Remove 7.13.0 coming tag (#1668)

- docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
- [DOCS] Remove 7.12.1 coming tag (#1648)
> [master] [DOCS] Remove 7.12.1 coming tag (#1648)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
- spring.io/plugin-release has been deprecated and need to be replaced with
spring.io/plugin-release-local
Fixes #1669
> Fix spring io repository usage

- docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
- [DOCS] Remove 7.13.1 coming tag (#1677)
> [master] [DOCS] Remove 7.13.1 coming tag (#1677)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
- [DOCS] Remove 7.13.1 coming tag (#1677)
> [7.x] [DOCS] Remove 7.13.1 coming tag (#1677)

- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
A change that went in a while ago has made changes to the wildcard query functionality. It now functions as it had historically. This PR updates the testing logic to make sure the wildcard tests account for these differences.
> Fix failing strict wildcard pushdown tests

- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- Fix failing strict wildcard pushdown tests (#1683)
> [7.x] Fix failing strict wildcard pushdown tests (#1683)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
- [DOCS] Remove 7.13.2 coming tag (#1690)
> [master] [DOCS] Remove 7.13.2 coming tag (#1690)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
- [DOCS] Remove 7.13.2 coming tag (#1690)
> [7.x] [DOCS] Remove 7.13.2 coming tag (#1690)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- hive/build.gradle
Snapshot builds and CI is failing because a dependency cannot be reliably pulled from the repository it is in. The locations it is persisted in are either inaccessible or being sunset, and we luckily do not even use it, so this PR removes it from being considered by the build.
> Remove problem dependency

- mr/src/main/java/org/elasticsearch/hadoop/handler/impl/elasticsearch/ElasticsearchHandler.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
- mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
- mr/src/test/java/org/elasticsearch/hadoop/util/EsMajorVersionTest.java
This PR ensures that ES-Hadoop is running against a verified Elasticsearch deployment during start up. The check ensures response format compatibility and protocol compliance with the server. The change also has ES-Hadoop warn on mismatched internal configurations for the cluster.
Closes #1672
> Verify cluster main info response returns correct product headers

- mr/src/main/java/org/elasticsearch/hadoop/handler/impl/elasticsearch/ElasticsearchHandler.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
- mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
- mr/src/test/java/org/elasticsearch/hadoop/util/EsMajorVersionTest.java
- Verify cluster main info response returns correct product headers (#1679)
> [7.x] Verify cluster main info response returns correct product headers (#1679)

- docs/src/reference/asciidoc/core/arch.adoc
- docs/src/reference/asciidoc/core/mr.adoc
We'll be removing the ES glossary with https://github.com/elastic/elasticsearch/pull/74579.
This updates a few references to point to the Stack glossary.
> [DOCS] Update ES glossary references

- docs/src/reference/asciidoc/core/arch.adoc
- docs/src/reference/asciidoc/core/mr.adoc
- [DOCS] Update ES glossary references (#1700)
> [7.x] [DOCS] Update ES glossary references (#1700)

- docs/src/reference/asciidoc/core/arch.adoc
- docs/src/reference/asciidoc/core/mr.adoc
Backports the following commits to 7.13:
- [DOCS] Update ES glossary references (#1700)
> [7.13] [DOCS] Update ES glossary references (#1700)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Added RNs for 7.13.3 (#1707)
> [master] [DOCS] Added RNs for 7.13.3 (#1707)

- buildSrc/build.gradle
We need to explicitly add the former transitive dependencies of commons codec and ant-rat to the buildSrc compile classpath as the code relying on this has moved directly to buildSrc here.
> Fix buildSrc classpath after build-tools refactoring

- buildSrc/build.gradle
- Fix buildSrc classpath after build-tools refactoring (#1705)
> [7.x] Fix buildSrc classpath after build-tools refactoring (#1705)

- buildSrc/build.gradle
Backports the following commits to 7.14:
- Fix buildSrc classpath after build-tools refactoring (#1705)
> [7.14] Fix buildSrc classpath after build-tools refactoring (#1705)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
- [DOCS] Remove 7.13.4 coming tag (#1721)
> [master] [DOCS] Remove 7.13.4 coming tag (#1721)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
Backports the following commits to 7.14:
- [DOCS] Remove 7.13.4 coming tag (#1721)
> [7.14] [DOCS] Remove 7.13.4 coming tag (#1721)

- docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
- [DOCS] Remove 7.13.4 coming tag (#1721)
> [7.x] [DOCS] Remove 7.13.4 coming tag (#1721)

- docs/src/reference/asciidoc/appendix/release-notes/7.14.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.14.0 release notes (#1727)
> [7.x] [DOCS] Add 7.14.0 release notes (#1727)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/ElasticsearchFixturePlugin.groovy
- test/shared/src/main/resources/test.properties
Recently the ES-Hadoop builds have started failing due to 401 Unauthorized exceptions. This seems to be related to recent changes to enable security by default (https://github.com/elastic/elasticsearch/pull/75816).
This PR updates the ES fixture in ES-Hadoop to enable security and use basic authentication within all the integration tests.
> Enable minimal security for ES testing fixtures

- docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
This PR removes the "coming" qualification from the 7.14.1 Elasticsearch for Apache Hadoop release notes.
> [DOCS] Remove coming tag from 7.14.1 release notes

- mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
The check for the X-elastic-product header is currently case sensitive. However header names are
supposed to be case-insensitive. This commit makes the check case sensitive.
Relates #1745
> Using case-insensitive headers

- mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
The check for the X-elastic-product header is currently case sensitive. However header names are
supposed to be case-insensitive. This commit makes the check case sensitive.
Relates #1745
> Using case-insensitive headers (#1744)

- docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 7.14.1 release notes (#1740)
> [7.x] [DOCS] Add 7.14.1 release notes (#1740)

- docs/src/reference/asciidoc/appendix/release-notes/7.14.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
This commit adds a known issue to the 7.14.0 release notes about the case sensitivity of the X-elastic-product header
in 7.14.0 and 7.14.1.
Relates #1745 #1672
> Adding a known issue about X-elastic-product case sensitivity

- mr/build.gradle
- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/HadoopSettings.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- spark/core/build.gradle
- spark/core/src/main/scala/org/elasticsearch/spark/cfg/SparkSettings.java
- spark/core/src/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDDIterator.scala
- spark/core/src/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
- spark/core/src/test/scala/org/elasticsearch/spark/cfg/SparkConfigTest.scala
This commit adds a X-Opaque-ID header when contacting Elasticsearch for es-hadoop or es-spark.
> Setting X-Opaque-ID header for all reads and writes for mapreduce and spark

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [DOCS] Release notes for 8.0.0-beta1 (#1786)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- gradle/wrapper/gradle-wrapper.properties
- test/fixtures/minikdc/build.gradle
Gradle has deprecated several features, and irritatingly it fails the build if you use those features without passing
the "--warning-mode=none" argument. This commit replaces those deprecated things so that you can run the build
without passing "--warning-mode=none".
> Getting rid of gradle deprecation warnings

- .ci/java-versions.properties
Elasticsearch 8.0+ requires Java 17 now so we need to bump the runtime Java version used for integration tests appropriately.
> Bump runtime java to 17

- .ci/java-versions.properties
- Bump runtime java to 17 (#1791)
> [8.0] Bump runtime java to 17 (#1791)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- gradle/wrapper/gradle-wrapper.properties
- test/fixtures/minikdc/build.gradle
Gradle has deprecated several features, and irritatingly it fails the build if you use those features
without passing the "--warning-mode=none" argument. This commit replaces those deprecated
things so that you can run the build without passing "--warning-mode=none".
> Getting rid of gradle deprecation warnings (#1792)

- spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- Fix script update tests in Spark (#1783)
> [8.0] Fix script update tests in Spark (#1783)

- gradle/wrapper/gradle-wrapper.properties
Gradle 7.2 causes failures building our scala 2.10 artifacts. This commit rolls it back to 7.1, which seems to work fine.
> Backing up gradle to a version that works with scala 2.10

- gradle/wrapper/gradle-wrapper.properties
Gradle 7.2 causes failures building our scala 2.10 artifacts. This commit rolls it back to 7.1, which
seems to work fine.
> Backing up gradle to a version that works with scala 2.10 (#1797)

- gradle/wrapper/gradle-wrapper.properties
- spark/core/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
Building scala 2.10 code stopped working when I upgraded to gradle 7.2 (scala 2.11 and 2.12 continued working
fine). I still don't fully understand it, but the problem seems to be that the java boot classpath jars are no longer
getting into the scala boot classpath. I found that I had to set it in two ways: (1) I have to explicitly set it in
scalaCompileOptions.additionalParameters or the build fails and (2) I have to set it in options.bootstrapClasspath
or I get warnings from javac that its boot classpath is incompatible with the source version. The two commands
I've been using to test this out are:
```
./gradlew :elasticsearch-spark:compileSpark13scala210Scala
```
and
```
./gradlew :elasticsearch-spark:test
```
> Setting java boot classpath so that scala 2.10 works on gradle 7.2

- hive/build.gradle
- pig/build.gradle
- spark/core/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- test/shared/build.gradle
This commit adds support for building on java 17, while leaving support for building java 11 untouched.
> builds with java 17

- mr/src/main/java/org/elasticsearch/hadoop/mr/WritableValueReader.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/FieldType.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueReader.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
- mr/src/main/java/org/elasticsearch/hadoop/util/DateUtils.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/builder/JdkValueReaderTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriterTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
- mr/src/test/java/org/elasticsearch/hadoop/util/DateUtilsTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typed/primitives.json
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typeless/primitives.json
- spark/core/build.gradle
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueReaderTest.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
Adding support for the date_nanos field type. This field type is now treated in the same way as the date field type.
Closes #1653
> Adding support for the date_nanos field type

- .ci/java-versions.properties
We are bumping the compiler version of [Elasticsearch to Java 17](https://github.com/elastic/elasticsearch/pull/80851) meaning that `build-tools` will now target Java 17. For this not to break elasticsearch-hadoop, we need to start building it with Java 17 as well.
> Build Hadoop with Java 17

- gradle.properties
[CVE-2021-44228] Log4j versions prior to 2.15.0 are subject to a remote code execution vulnerability via the ldap JNDI parser.
> Bump: log4j 2.10.0 to 2.15.0

- gradle.properties
- Bump Internal usages of log4j 2.10.0 to 2.15.0 (#1817)
> [8.0] Bump Internal usages of log4j 2.10.0 to 2.15.0 (#1817)

- spark/core/build.gradle
With the Spark 3.2 upgrade work we needed to remove an old dependency rule that was breaking runtime classpaths in the tests for Spark. This rule was removed in the Spark SQL 3 project but was not updated in the Core Spark project. This PR removes the rule to fix the core Spark tests for Spark 3.x.
> Fix Spark 3.x test configurations

- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala
- spark/core/src/test/scala/org/elasticsearch/spark/ScalaExtendedBooleanValueReaderTest.scala
- spark/core/src/test/scala/org/elasticsearch/spark/ScalaValueReaderTest.scala
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
By default we intend to treat empty fields as nulls when being read in through spark sql. However we actually
turn them into None objects, which causes spark-sql to blow up. This commit treats them as nulls.
Closes #1635
> Correctly reading empty fields in as null rather than throwing exception

- docs/src/reference/asciidoc/core/spark.adoc
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
The documentation for es.read.fields.include left room for confusion.  Also the bevaior was different between spark 1,
spark 2, and spark 3 -- setting "es.read.fields.include" to _part_ of a hierarchy caused a NullPointerException in spark 1
and spark 2.
Closes #1784
> Improving documentation about es.read.fields.include, and fixing a related bug

- docs/src/reference/asciidoc/appendix/release-notes/7.16.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.17:
- [DOCS] Add 7.16.2 release notes (#1825)
> [7.17] [DOCS] Add 7.16.2 release notes (#1825)

- mr/src/main/java/org/elasticsearch/hadoop/mr/WritableValueReader.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/FieldType.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueReader.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
- mr/src/main/java/org/elasticsearch/hadoop/util/DateUtils.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/builder/JdkValueReaderTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriterTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
- mr/src/test/java/org/elasticsearch/hadoop/util/DateUtilsTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typed/primitives.json
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typeless/primitives.json
- spark/core/build.gradle
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueReaderTest.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
Adding support for the date_nanos field type. This field type is now treated in the same way as the date
field type, except that we keep track of nanoseconds.
Closes #1653
> Adding support for the date_nanos field type (#1803)

- docs/src/reference/asciidoc/core/spark.adoc
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
The documentation for es.read.fields.include left room for confusion. Also the bevaior was different between spark 1,
spark 2, and spark 3 -- setting "es.read.fields.include" to part of a hierarchy caused a NullPointerException in spark 1
and spark 2.
Closes #1784
> Improving documentation about es.read.fields.include, and fixing a related bug (#1822)

- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueReaderTest.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
This fixes some missing import statements in tests for the date_nanos fix (#1803)
Closes #1835
> Fixing imports for tests

- gradle.properties
Updating the log4j version to 2.17.0 since more vulnerabilities were found with 2.15.0.
> Updating log4j version

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
I originally included PR #1350 in the 8.0.0-alpha1 release notes. However, the changes in that PR were undone in #1471.
Relates to https://github.com/elastic/elasticsearch-hadoop/pull/1726.
> [DOCS] Remove PR #1350 from 8.0.0-alpha1 RNs

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
- [DOCS] Remove PR 1350 from 8.0.0-alpha1 RNs (#1846)
> [8.0] [DOCS] Remove PR 1350 from 8.0.0-alpha1 RNs (#1846)

- docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports the following commits to 7.17:
- [DOCS] Add 7.16.3 release notes (#1848)
> [7.17] [DOCS] Add 7.16.3 release notes (#1848)

- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/FilteringValueWriter.java
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
This PR fix the Scala Writer when it processes case classes with null fields.
Closes #998
> resolve saveToEs saves case classes fields with NULL values #998 (#1478)

- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
- spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
The code in ScalaValueWriter::doWriteScala was not compiling on the 7.17 branch. The problem is that the () reference to Unit was confusing the compiler. This commit makes the reference to Unit more explicit, and adds a test to make sure that Unit is being handled as expected.
> Fixing a scala compilation problem

- mr/src/main/java/org/elasticsearch/hadoop/serialization/FieldType.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typed/primitives.json
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
This commit adds support for wildcard fields in Elasticsearch mappings.
Closes #1697
> Adding support for wildcard fields

- mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/mapping.json
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/scroll.json
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
This commit makes it so that if an array is null in Elasticsearch, it comes into es-hadoop/spark as null. Previously
it showed up as either [] or [null], depending on spark version.
Closes #1527
> Fixing support for empty and null arrays

- mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typeless/primitives.json
MappingTest broke as a result of #1823. This commit fixes it.
> Fixing a unit test failure

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.0.0-rc1 release notes (#1859)
> [8.0] [DOCS] Add 8.0.0-rc1 release notes (#1859)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
- [DOCS] Remove 8.0.0-rc1 coming tag (#1861)
> [master] [DOCS] Remove 8.0.0-rc1 coming tag (#1861)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
When preparing the 8.0.0-rc1 release notes in #1859, I excluded PRs with the `v7.17` label. However, 7.17 hasn't been released yet so those PRs should be included. This adds the missing PRs.
> [DOCS] Add missing items to 8.0.0-rc1 release notes

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- qa/kerberos/build.gradle
This commit avoids gradle warnings when running ./gradlew :qa:kerberos:compileJava. The :qa:kerberos project
had been directly pulling in the itest.runtimeClasspath from the storm and hadoop-mr projects, which is not allowed
in gradle 8.
> Getting rid of direct cross-project dependencies to avoid gradle warnings (#1868)

- docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
Backports the following commits to 7.17:
- [DOCS] Remove coming tag from 7.16.3 release notes (#1852)
> [7.17] [DOCS] Remove coming tag from 7.16.3 release notes (#1852)

- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/test/java/org/elasticsearch/hadoop/cfg/SettingsTest.java
This commit strips out any non-visible, non-ascii characters from the X-Opaque-ID header.
Closes #1872
> Check for invalid characters in X-Opaque-ID headers

- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- mr/src/test/java/org/elasticsearch/hadoop/cfg/SettingsTest.java
This commit strips out any non-visible, non-ascii characters from the X-Opaque-ID header.
Closes #1872
> Check for invalid characters in X-Opaque-ID headers (#1873)

- mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
This commit adds support for "update" as the output mode for spark structured streaming to Elasticsearch.
Closes #1123
> Adding support for update output mode to structured streaming

- gradle.properties
- spark/core/build.gradle
- spark/core/src/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDD.scala
- spark/core/src/main/scala/org/elasticsearch/spark/rdd/JDKCollectionConvertersCompat.scala
- spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaMapFieldExtractor.scala
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
This commit adds support for spark 3.2 running scala 2.13.
Closes #1815
> Supporting scala 2.13 for spark 3.2.0

- mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/AbstractBulkFactory.java
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
- spark/sql-13/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
- spark/sql-20/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
- spark/sql-30/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
This commit adds support for upserts of nested array fields.
Closes #1190
> Adding support for upserts of nested arrays

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
- pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/package.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/streaming/EsSparkStreaming.scala
- storm/src/main/java/org/elasticsearch/storm/EsBolt.java
- storm/src/main/java/org/elasticsearch/storm/EsSpout.java
This commit deprecates spark 1.x, scala 2.10 on spark 2.x, hadoop 1, pig, and storm. Support will be removed for these things at a later date.
> Deprecating old technology

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
- pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/package.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/streaming/EsSparkStreaming.scala
- storm/src/main/java/org/elasticsearch/storm/EsBolt.java
- storm/src/main/java/org/elasticsearch/storm/EsSpout.java
This commit deprecates spark 1.x, scala 2.10 on spark 2.x, hadoop 1, pig, and storm. Support will be removed for these things at a later date.
> Deprecating old technology (#1845)

- mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMROldApiSaveTest.java
AbstractMROldApiSaveTest.testUpdateWithoutId broke when #1839 was merged because we are now failing earlier if
upsert is used but `es.mapping.id` is not set. The exception is now the same as the one you get when update is not
configured to use `es.mapping.id`.
Relates #1839 #69
> Expected exception when incorrectly configuring upsert has changed

- spark/core/src/itest/java/org/elasticsearch/spark/integration/AbstractHadoopBasicSparkTest.java
- spark/core/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkTest.java
- spark/core/src/itest/java/org/elasticsearch/spark/integration/ScalaUtils.java
- spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- spark/core/src/main/scala/org/elasticsearch/spark/rdd/JDKCollectionConvertersCompat.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
- spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
- spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkStreamingTest.java
- spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/ScalaUtils.java
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractJavaEsSparkStructuredStreamingTest.java
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsScalaSparkStreaming.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
- spark/sql-30/src/test/scala/org/elasticsearch/spark/sql/RowSerializationEventConverterTest.scala
This commit fixes several integration test problems caused by the introduction of scala 2.13 in #1841.
> Fixing scala 2.13 problems in integration tests

- mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
This commit fixes a bug that had been introduced to the "Documents Received" mapreduce counter. It had been
missing counting the first set of hits that were returned by each scroll.
Closes #1470
> Fixing docsReceived counter

- docs/src/reference/asciidoc/core/intro/requirements.adoc
- docs/src/reference/asciidoc/index.adoc
This commit makes several fixes to the requirements documentation, which had fallen out of date for java, hadoop, hive, and spark.
Closes #1843
> Fixing out of date requirements docs

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
- mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/no-scroll-id/scroll.json
This commit changes es-hadoop to treat frozen indices as empty indices rather than throwing exceptions. Before
this change if you query a frozen index with es-hadoop or spark you get job failure with an exception like this:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (localhost executor 2): org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid response
at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:60)
at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:272)
at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:263)
at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:313)
at …
```
> Avoiding failure when using frozen indices

- docs/src/reference/asciidoc/core/intro/requirements.adoc
- docs/src/reference/asciidoc/index.adoc
This commit makes several fixes to the requirements documentation, which had fallen out of date for java, hadoop, hive, and spark.
Closes #1843
> Fixing out of date requirements docs (#1844)

- mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
- mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
This commit fixes a bug that had been introduced to the "Documents Received" mapreduce counter. It had been
missing counting the first set of hits that were returned by each scroll.
Closes #1470
> Fixing docsReceived counter (#1840)

- mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/mapping.json
- mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/scroll.json
- spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
This commit makes it so that if an array is null in Elasticsearch, it comes into es-hadoop/spark as null. Previously
it showed up as either [] or [null], depending on spark version.
Closes #1527
> Fixing support for empty and null arrays (#1827)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
https://elasticsearch-hadoop_1892.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.0.0-rc2.html
> [DOCS] Add 8.0.0-rc2 release notes

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.0.0-rc2 release notes (#1892)
> [8.0] [DOCS] Add 8.0.0-rc2 release notes (#1892)

- mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/AbstractBulkFactory.java
AbstractBulkFactory currently ignores the results of certain writes, meaning that a user might corrupt or lose data without realizing it. This commit checks the result and explicitly throws an Exception if there is a problem.
> Checking result of bulk writes

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
- [DOCS] Remove 8.0.0-rc2 coming tag (#1894)
> [8.1] [DOCS] Remove 8.0.0-rc2 coming tag (#1894)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
- [DOCS] Remove 8.0.0-rc2 coming tag (#1894)
> [8.0] [DOCS] Remove 8.0.0-rc2 coming tag (#1894)

- docs/src/reference/asciidoc/core/mapping.adoc
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/RowValueReader.scala
Es-hadoop does not support fields with dots in their names (#853). Adding support is likely to cause more problems
than it fixes. So this PR documents that we do not support them, and adds a better error message.
> Documenting that we do not support dots in field names

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Adds the 8.0.0 GA release notes. I created these by combining the 8.0.0-alpha1, -alpha2, -beta1, -rc1 and -rc2 releases notes. Copy/paste may have been involved.
https://elasticsearch-hadoop_1902.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/8.0/eshadoop-8.0.0.html
> [DOCS] Add 8.0.0 GA release notes

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.0.0 GA release notes (#1902)
> [8.1] [DOCS] Add 8.0.0 GA release notes (#1902)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.0.0 GA release notes (#1902)
> [master] [DOCS] Add 8.0.0 GA release notes (#1902)

- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Calling refresh() in an integration test so that it consistently succeeds.
Relates #1900
> Fixing testDotsInFieldNames

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc
- [DOCS] Remove 8.0.0 coming tag (#1907)
> [master] [DOCS] Remove 8.0.0 coming tag (#1907)

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc
- [DOCS] Remove 8.0.0 coming tag (#1907)
> [8.1] [DOCS] Remove 8.0.0 coming tag (#1907)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.0.1 release notes (#1910)
> [8.1] [DOCS] Add 8.0.1 release notes (#1910)

- docs/src/reference/asciidoc/appendix/release-notes/8.1.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
https://elasticsearch-hadoop_1911.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/8.1/eshadoop-8.1.0.html
> [DOCS] Add 8.1.0 release notes

- docs/src/reference/asciidoc/appendix/release-notes/8.1.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.1.0 release notes (#1911)
> [master] [DOCS] Add 8.1.0 release notes (#1911)

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
This commit logs a warning instead of throwing an exception if an attempt to flush before writing is made (which our
Storm implementation can do).
Closes #1357
> Do not fail if flush is called before any writes

- docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc
- [DOCS] Remove 8.0.1 coming tag (#1914)
> [master] [DOCS] Remove 8.0.1 coming tag (#1914)

- docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc
- [DOCS] Remove 8.0.1 coming tag (#1914)
> [8.1] [DOCS] Remove 8.0.1 coming tag (#1914)

- qa/kerberos/build.gradle
It looks like `:qa:kerberos:setupUsers` fails on a clean installation because it has an implicit dependency on the :qa:kerberos code having been built. This commit adds an explicit dependency. I happened to stumble on this while tracking down other problems, but I don't think it impacts any of our normal builds.
> Adding an explicit dependency on jar to setupUsers

- docs/src/reference/asciidoc/appendix/release-notes/8.1.0.adoc
- [DOCS] Remove 8.1.0 coming tag (#1916)
> [master] [DOCS] Remove 8.1.0 coming tag (#1916)

- docs/src/reference/asciidoc/appendix/release-notes/8.1.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.1.1 release notes (#1930)
> [master] [DOCS] Add 8.1.1 release notes (#1930)

- qa/kerberos/build.gradle
- qa/kerberos/src/itest/java/org/elasticsearch/hadoop/qa/kerberos/AbstractClusterVerificationTests.java
- qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/LoadToES.scala
- qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/ReadFromES.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
This PR adds the requisite configuration step for the UserProvider implementation before attempting to discover the cluster information in the SparkSQL integrations. This additionally updates the integration tests to add coverage for the write and read paths for SparkSQL.
Fixes #1933
> Set UserProvider before discovery in Spark SQL integrations

- qa/kerberos/build.gradle
- qa/kerberos/src/itest/java/org/elasticsearch/hadoop/qa/kerberos/AbstractClusterVerificationTests.java
- qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/LoadToES.scala
- qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/ReadFromES.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
> [7.17] Set UserProvider before discovery in Spark SQL integrations (#1934)

- docs/src/reference/asciidoc/appendix/release-notes/8.1.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [DOCS] Add 8.1.1 release notes (#1938)
> [8.1] [DOCS] Add 8.1.1 release notes (#1938)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HadoopServiceDescriptor.groovy
It looks like 3.3.0 is no longer available for download at https://dlcdn.apache.org/hadoop/common/, so updating to the latest.
> Updating the Hadoop fixture version to 3.3.2

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HadoopServiceDescriptor.groovy
3.3.0 is no longer available for download
> Updating hadoop fixture version to 3.3.2 (#1944)

- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
In #1803 we added support for the `data_nanos` Elasticsearch field type. However there is a bug in that sets the zone offset to the offset right now, as opposed to what the zone offset was at the time of the date. So for example if the date was `2015-01-01T06:10:30.123456789-06:00`, then if you read that date after daylight saving had begun you would see it as `2015-01-01T06:10:30.123456789-05:00`.
> Fixing DST bug in data_nanos support

- mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
In #1803 we added support for the data_nanos Elasticsearch field type. However there is a bug in that sets the zone offset to the offset right now, as opposed to what the zone offset was at the time of the date. So for example if the date was 2015-01-01T06:10:30.123456789-06:00, then if you read that date after daylight saving had begun you would see it as 2015-01-01T06:10:30.123456789-05:00.
> Fixing DST bug in data_nanos support (#1943)

- .ci/java-versions.properties
- hive/build.gradle
- pig/build.gradle
- spark/core/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- test/shared/build.gradle
Backporting support for building on java 17 from #1802 and #1808
> Backport java 17 build support to 7.17

- docs/src/reference/asciidoc/appendix/release-notes/8.1.2.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Forward-fits https://github.com/elastic/elasticsearch-hadoop/pull/1938 and https://github.com/elastic/elasticsearch-hadoop/pull/1951
> [DOCS] Add missing 8.1.2 and 8.1.3 release notes in 8.2

- docs/src/reference/asciidoc/appendix/release-notes/8.2.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
Backports https://github.com/elastic/elasticsearch-hadoop/pull/1956
> [8.2][DOCS] Add 8.2.0 release notes (#1956)

- docs/src/reference/asciidoc/appendix/release-notes/8.2.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.2`:
- [[DOCS] Add 8.2.1 release notes (#1960)](https://github.com/elastic/elasticsearch-hadoop/pull/1960)
> [8.2] [DOCS] Add 8.2.1 release notes (#1960)

- docs/src/reference/asciidoc/appendix/release-notes/8.2.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.2`:
- [[DOCS] Add 8.2.2 release notes (#1963)](https://github.com/elastic/elasticsearch-hadoop/pull/1963)
> [8.2] [DOCS] Add 8.2.2 release notes (#1963)

- docs/src/reference/asciidoc/appendix/release-notes/8.2.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.3`:
- [[DOCS] Add 8.2.2 release notes (#1963)](https://github.com/elastic/elasticsearch-hadoop/pull/1963)
> [8.3] [DOCS] Add 8.2.2 release notes (#1963)

- docs/src/reference/asciidoc/appendix/release-notes/8.3.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.3`:
- [[DOCS] Add 8.3.1 release notes (#1975)](https://github.com/elastic/elasticsearch-hadoop/pull/1975)
> [8.3] [DOCS] Add 8.3.1 release notes (#1975)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
- gradle/wrapper/gradle-wrapper.properties
- hive/src/itest/java/org/elasticsearch/hadoop/integration/hive/HiveEmbeddedServer2.java
- mr/build.gradle
- spark/core/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
The ES project recently upgraded Gradle and now some build code from ES depends on new methods.
Additionally, the Spark version in QA has disappeared and a new version of Spark needs to be added for testing.
> Upgrade to Gradle 7.5

- docs/src/reference/asciidoc/appendix/release-notes/8.3.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.4`:
- [[DOCS] Add 8.3.3 release notes (#1983)](https://github.com/elastic/elasticsearch-hadoop/pull/1983)
> [8.4] [DOCS] Add 8.3.3 release notes (#1983)

- docs/src/reference/asciidoc/appendix/release-notes/8.3.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.3`:
- [[DOCS] Add 8.3.3 release notes (#1983)](https://github.com/elastic/elasticsearch-hadoop/pull/1983)
> [8.3] [DOCS] Add 8.3.3 release notes (#1983)

- gradle/wrapper/gradle-wrapper.properties
It looks like this commit https://github.com/elastic/elasticsearch/pull/88595/files#diff-b02217a5b8647aa4eda31838ce5ff2fb75a8e7056932ccb62220313defdb9e95R93 in https://github.com/elastic/elasticsearch/pull/88595 caused the 7.17 es-hadoop build to fail because it's using a method that's not in gradle 7.3. Here's the stack trace we were seeing in `./gradlew build integrationTest --stacktrace`:
```
2022-08-15T16:13:53.280-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.NoSuchMethodError: 'org.gradle.internal.resources.ResourceLock org.gradle.internal.resources.SharedResource.getResourceLock()'
2022-08-15T16:13:53.280-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.elasticsearch.gradle.testclusters.StandaloneRestIntegTestTask.getSh …
```
> Upgrading to gradle 7.5.1

- mr/build.gradle
- spark/core/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
Tests that use securmock currently fail with exceptions like the one below. This fixes the build to let securemock work, the same way we did in #1980.
```
java.lang.ExceptionInInitializerError
at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
at …
```
> Fixing the build for securemock on java 17

- docs/src/reference/asciidoc/appendix/release-notes/8.4.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.4`:
- [[DOCS] Add 8.4.0 release notes (#1989)](https://github.com/elastic/elasticsearch-hadoop/pull/1989)
> [8.4] [DOCS] Add 8.4.0 release notes (#1989)

- mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/HadoopSettings.java
- mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
- spark/core/src/main/scala/org/elasticsearch/spark/cfg/SparkSettings.java
Adding a simple user agent that contains just es-hadoop version information and hadoop or spark version information. For example:
```
elasticsearch-hadoop/8.5.0-SNAPSHOT spark/1.6.2
```
> Adding a user-agent header

- mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
- spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
Fixing the behavior of the `es.index.read.missing.as.empty` setting if one or more indices exist and one or more do not. Previously if any index in the list of indices was missing it would return no results. Now it returns results from indices that do exist and ignores indices that do not exist. Behavior is unchanged if this property is unset or set to false.
Closes #1055
> Ignoring missing indices if es.index.read.missing.as.empty is true

- docs/src/reference/asciidoc/appendix/release-notes/8.4.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.4`:
- [[DOCS] Add 8.4.2 release notes (#1998)](https://github.com/elastic/elasticsearch-hadoop/pull/1998)
> [8.4] [DOCS] Add 8.4.2 release notes (#1998)

- docs/src/reference/asciidoc/appendix/release-notes/8.4.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.5`:
- [[DOCS] Add 8.4.3 release notes (#2028)](https://github.com/elastic/elasticsearch-hadoop/pull/2028)
> [8.5] [DOCS] Add 8.4.3 release notes (#2028)

- docs/src/reference/asciidoc/appendix/release-notes/8.5.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.5`:
- [[DOCS] Add 8.5.0 release notes (#2032)](https://github.com/elastic/elasticsearch-hadoop/pull/2032)
> [8.5] [DOCS] Add 8.5.0 release notes (#2032)

- docs/src/reference/asciidoc/appendix/release-notes/8.5.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.5`:
- [[DOCS] Add 8.5.1 release notes (#2040)](https://github.com/elastic/elasticsearch-hadoop/pull/2040)
> [8.5] [DOCS] Add 8.5.1 release notes (#2040)

- docs/src/reference/asciidoc/appendix/release-notes/8.5.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.5.2 release notes (#2042)](https://github.com/elastic/elasticsearch-hadoop/pull/2042)
> [8.6] [DOCS] Add 8.5.2 release notes (#2042)

- docs/src/reference/asciidoc/appendix/release-notes/8.5.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.5.3 release notes (#2045)](https://github.com/elastic/elasticsearch-hadoop/pull/2045)
> [8.6] [DOCS] Add 8.5.3 release notes (#2045)

- docs/src/reference/asciidoc/appendix/release-notes/8.6.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.6.0 release notes (#2053)](https://github.com/elastic/elasticsearch-hadoop/pull/2053)
> [8.6] [DOCS] Add 8.6.0 release notes (#2053)

- docs/src/reference/asciidoc/appendix/release-notes/8.6.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.6.1 release notes (#2059)](https://github.com/elastic/elasticsearch-hadoop/pull/2059)
> [8.6] [DOCS] Add 8.6.1 release notes (#2059)

- docs/src/reference/asciidoc/appendix/release-notes/8.6.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.7`:
- [[DOCS] Add 8.6.2 release notes (#2064)](https://github.com/elastic/elasticsearch-hadoop/pull/2064)
> [8.7] [DOCS] Add 8.6.2 release notes (#2064)

- docs/src/reference/asciidoc/appendix/release-notes/8.6.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.6.2 release notes (#2064)](https://github.com/elastic/elasticsearch-hadoop/pull/2064)
> [8.6] [DOCS] Add 8.6.2 release notes (#2064)

- mr/src/main/java/org/elasticsearch/hadoop/mr/SafeWritableConverter.java
- mr/src/main/java/org/elasticsearch/hadoop/mr/WritableBytesConverter.java
- mr/src/test/java/org/elasticsearch/hadoop/mr/WritableBytesConverterTests.java
This fixes two bugs in `WritableBytesConverter::convert`:
1. If the `from` is a BytesWritable then we first correctly copy its bytes to `to` in `SafeWritableConverter`, and then we incorrectly copy the bytes for the string representation of the byte array into `to` in `JdkBytesConverter` (so a performance problem plus the wrong data in `to`).
2. If the `from` is a Text then we first correctly copy its bytes to `to` in `SafeWritableConverter`, and then we incorrectly copy the string value of `from` into a byte array that might be larger than expected in `JdkBytesConverter` (so a performance problem plus a result array in `to` that is too large).
It looks like this was caused by #937
Closes #2072
> FIxing WritableBytesConverter to not overwrite bytes with wrong value

- docs/src/reference/asciidoc/appendix/release-notes/8.7.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.8`:
- [[DOCS] Add 8.7.1 release notes (#2084)](https://github.com/elastic/elasticsearch-hadoop/pull/2084)
> [8.8] [DOCS] Add 8.7.1 release notes (#2084)

- docs/src/reference/asciidoc/appendix/release-notes/8.8.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `main` to `8.8`:
- [[DOCS] Add 8.8.0 release notes (#2093)](https://github.com/elastic/elasticsearch-hadoop/pull/2093)
> [8.8] [DOCS] Add 8.8.0 release notes (#2093)

- docs/src/reference/asciidoc/appendix/release-notes/8.8.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
8.8 backport of https://github.com/elastic/elasticsearch-hadoop/pull/2097
> [8.8] [DOCS] Add 8.8.1 release notes

- docs/src/reference/asciidoc/appendix/release-notes/8.8.1.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.8.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.2.2 release notes (#2103)](https://github.com/elastic/elasticsearch-hadoop/pull/2103)
> [8.9] [DOCS] Add 8.2.2 release notes (#2103)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/HadoopClusterConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/ProcessConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/RoleConfiguration.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/conf/ServiceConfiguration.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/info/GlobalBuildInfoPlugin.java
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
- dist/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- test/fixtures/minikdc/build.gradle
Keep Hadoop build in sync with elasticsearch build. This required fixing some deprecation.
> Update gradle wrapper to 8.2

- docs/src/reference/asciidoc/appendix/release-notes/8.9.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
https://elasticsearch-hadoop_2110.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.9.0.html
> [DOCS] Add 8.9.0 release notes

- docs/src/reference/asciidoc/appendix/release-notes/8.9.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.9.0 release notes (#2110)](https://github.com/elastic/elasticsearch-hadoop/pull/2110)
> [8.9] [DOCS] Add 8.9.0 release notes (#2110)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
This fixes the broken pom file generation after the Gradle 8.2 update
> Fix pom file naming after Gradle update

- catalog-info.yml
I need to write Vault secrets for the work going on in #2114, but I don't believe I can do it until this repo has a catalog-info file. This is the file that holds the top-level Buildkite pipeline definitions.
So, I'm splitting it out from the other PR, and taking the triggers off for now.
> [buildkite] Add initial catalog-info.yml

- docs/src/reference/asciidoc/appendix/release-notes/8.9.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.9.1 release notes (#2122)](https://github.com/elastic/elasticsearch-hadoop/pull/2122)
> [8.9] [DOCS] Add 8.9.1 release notes (#2122)

- docs/src/reference/asciidoc/appendix/release-notes/8.9.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.9.1 release notes (#2122)](https://github.com/elastic/elasticsearch-hadoop/pull/2122)
> [8.10] [DOCS] Add 8.9.1 release notes (#2122)

- .buildkite/branches.sh
- .buildkite/dra-workflow.trigger.sh
- .buildkite/dra-workflow.yml
- .buildkite/dra.sh
- .buildkite/hooks/pre-command
- .buildkite/pipeline.py
- .buildkite/pull-requests.json
- .buildkite/tests.trigger.sh
- .gitignore
- catalog-info.yaml
- spark/core/build.gradle
- [Migrate CI pipelines to Buildkite (#2114)](https://github.com/elastic/elasticsearch-hadoop/pull/2114)
> [8.9] Migrate CI pipelines to Buildkite (#2114)

- .buildkite/branches.sh
- .buildkite/dra-workflow.trigger.sh
- .buildkite/dra-workflow.yml
- .buildkite/dra.sh
- .buildkite/hooks/pre-command
- .buildkite/pipeline.py
- .buildkite/pull-requests.json
- .buildkite/tests.trigger.sh
- .gitignore
- catalog-info.yaml
- spark/core/build.gradle
- [Migrate CI pipelines to Buildkite (#2114)](https://github.com/elastic/elasticsearch-hadoop/pull/2114)
> [7.17] Migrate CI pipelines to Buildkite (#2114)

- .buildkite/dra-workflow.yml
- [Fix dra-workflow pipeline spacing (#2125)](https://github.com/elastic/elasticsearch-hadoop/pull/2125)
- Add missing agent config to pipeline (b0ad5c08)
> [7.17] Fix dra-workflow pipeline spacing (#2125) | Add missing agent config to pipeline

- .buildkite/dra-workflow.yml
- [Fix dra-workflow pipeline spacing (#2125)](https://github.com/elastic/elasticsearch-hadoop/pull/2125)
- Add missing agent config to pipeline (b0ad5c08)
> [8.9] Fix dra-workflow pipeline spacing (#2125) | Add missing agent config to pipeline

- docs/src/reference/asciidoc/appendix/release-notes/8.9.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.9.2 release notes (#2129)](https://github.com/elastic/elasticsearch-hadoop/pull/2129)
> [8.10] [DOCS] Add 8.9.2 release notes (#2129)

- docs/src/reference/asciidoc/appendix/release-notes/8.10.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.10.0 release notes (#2134)](https://github.com/elastic/elasticsearch-hadoop/pull/2134)
> [8.10] [DOCS] Add 8.10.0 release notes (#2134)

- docs/src/reference/asciidoc/appendix/release-notes/8.10.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.10.1 release notes (#2136)](https://github.com/elastic/elasticsearch-hadoop/pull/2136)
> [8.10] [DOCS] Add 8.10.1 release notes (#2136)

- docs/src/reference/asciidoc/appendix/release-notes/8.10.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.10.2 release notes (#2138)](https://github.com/elastic/elasticsearch-hadoop/pull/2138)
> [8.10] [DOCS] Add 8.10.2 release notes (#2138)

- gradle/wrapper/gradle-wrapper.properties
Turns out the gradle distribution checksum check is only done on downloads and not reevaluated from cached downloads. This results in false positives for wrong checksums in gradle wrapper properties.
> Fix gradle bin checksum

- mr/src/itest/java/org/elasticsearch/hadoop/rest/pooling/AbstractTransportPoolTest.java
- mr/src/main/java/org/elasticsearch/hadoop/rest/pooling/TransportPool.java
As reported in #1362, when es-hadoop is making requests on behalf of another user, the TransportPool.validate() method incorrectly throws an exception rather than recognizing that the connection is bad and just returning false. The reason is that as of #1244, the exception being thrown in this case is not an IOException but an EsHadoopException with an IOException as its cause. This change checks for that and correctly returns false.
> Correctly handling EsHadoopException in TransportPool.validate()

- docs/src/reference/asciidoc/appendix/release-notes/8.11.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.0 release notes (#2154)](https://github.com/elastic/elasticsearch-hadoop/pull/2154)
> [8.11] [DOCS] Add 8.11.0 release notes (#2154)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.1 release notes (#2160)](https://github.com/elastic/elasticsearch-hadoop/pull/2160)
> [8.11] [DOCS] Add 8.11.1 release notes (#2160)

- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
This PR is meant to fix #2157 
The solution employed is to always resolve the current field name in the value reader when creating Row objects inside of arrays.
Tests were expanded to ensure that no other code was relying on this erroneous behavior. All instances of this happening in the test environment have been cleaned up, further validation put in place, and have had the incorrect behavior confirmed.
> Always resolve current field name in SparkSQL when creating Row objects inside of arrays

- spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
- spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowValueReader.scala
- [Always resolve current field name in SparkSQL when creating Row objects inside of arrays (#2158)](https://github.com/elastic/elasticsearch-hadoop/pull/2158)
> [8.11] Always resolve current field name in SparkSQL when creating Row objects inside of arrays (#2158)

- gradle/wrapper/gradle-wrapper.properties
- [Update gradle wrapper to 8.5 (#2168)](https://github.com/elastic/elasticsearch-hadoop/pull/2168)
> [8.11] Update gradle wrapper to 8.5 (#2168)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/DfsCopy.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy
- [Fix incompatibility to TestClusterAware api change (#2163)](https://github.com/elastic/elasticsearch-hadoop/pull/2163)
> [7.17] Fix incompatibility to TestClusterAware api change (#2163)

- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/ConcatFilesTask.java
- dist/build.gradle
- [Fix Gradle 8 deprecation warnings (#2071)](https://github.com/elastic/elasticsearch-hadoop/pull/2071)
> [7.17] Fix Gradle 8 deprecation warnings (#2071)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- [Fix pom file naming after Gradle update (#2115)](https://github.com/elastic/elasticsearch-hadoop/pull/2115)
> [7.17] Fix pom file naming after Gradle update (#2115)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.2 release notes (#2180)](https://github.com/elastic/elasticsearch-hadoop/pull/2180)
> [8.11] [DOCS] Add 8.11.2 release notes (#2180)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.2 release notes (#2180)](https://github.com/elastic/elasticsearch-hadoop/pull/2180)
> [8.12] [DOCS] Add 8.11.2 release notes (#2180)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.3 release notes (#2183)](https://github.com/elastic/elasticsearch-hadoop/pull/2183)
> [8.12] [DOCS] Add 8.11.3 release notes (#2183)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.3 release notes (#2183)](https://github.com/elastic/elasticsearch-hadoop/pull/2183)
> [8.11] [DOCS] Add 8.11.3 release notes (#2183)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.4 release notes (#2189)](https://github.com/elastic/elasticsearch-hadoop/pull/2189)
> [8.12] [DOCS] Add 8.11.4 release notes (#2189)

- docs/src/reference/asciidoc/appendix/release-notes/8.11.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.11.4 release notes (#2189)](https://github.com/elastic/elasticsearch-hadoop/pull/2189)
> [8.11] [DOCS] Add 8.11.4 release notes (#2189)

- docs/src/reference/asciidoc/appendix/release-notes/8.12.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.12.0 release notes (#2192)](https://github.com/elastic/elasticsearch-hadoop/pull/2192)
> [8.12] [DOCS] Add 8.12.0 release notes (#2192)

- docs/src/reference/asciidoc/appendix/release-notes/8.12.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.12.1 release notes (#2195)](https://github.com/elastic/elasticsearch-hadoop/pull/2195)
> [8.12] [DOCS] Add 8.12.1 release notes (#2195)

- docs/src/reference/asciidoc/appendix/release-notes/8.12.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.12.2 release notes (#2202)](https://github.com/elastic/elasticsearch-hadoop/pull/2202)
> [8.12] [DOCS] Add 8.12.2 release notes (#2202)

- docs/src/reference/asciidoc/appendix/release-notes/8.12.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.12.2 release notes (#2202)](https://github.com/elastic/elasticsearch-hadoop/pull/2202)
> [8.13] [DOCS] Add 8.12.2 release notes (#2202)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.0 release notes (#2205)](https://github.com/elastic/elasticsearch-hadoop/pull/2205)
> [8.13] [DOCS] Add 8.13.0 release notes (#2205)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.1 release notes (#2211)](https://github.com/elastic/elasticsearch-hadoop/pull/2211)
> [8.13] [DOCS] Add 8.13.1 release notes (#2211)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.2 release notes (#2218)](https://github.com/elastic/elasticsearch-hadoop/pull/2218)
> [8.13] [DOCS] Add 8.13.2 release notes (#2218)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.4 release notes (#2226)](https://github.com/elastic/elasticsearch-hadoop/pull/2226)
> [8.13] [DOCS] Add 8.13.4 release notes (#2226)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.3 release notes (#2223)](https://github.com/elastic/elasticsearch-hadoop/pull/2223)
> [8.14] [DOCS] Add 8.13.3 release notes (#2223)

- docs/src/reference/asciidoc/appendix/release-notes/8.13.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.13.4 release notes (#2226)](https://github.com/elastic/elasticsearch-hadoop/pull/2226)
> [8.14] [DOCS] Add 8.13.4 release notes (#2226)

- docs/src/reference/asciidoc/appendix/release-notes/8.14.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.14.0 release notes (#2233)](https://github.com/elastic/elasticsearch-hadoop/pull/2233)
> [8.14] [DOCS] Add 8.14.0 release notes (#2233)

- docs/src/reference/asciidoc/appendix/release-notes/8.14.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.14.1 release notes (#2239)](https://github.com/elastic/elasticsearch-hadoop/pull/2239)
> [8.14] [DOCS] Add 8.14.1 release notes (#2239)

- docs/src/reference/asciidoc/appendix/release-notes/8.14.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.14.2 release notes (#2242)](https://github.com/elastic/elasticsearch-hadoop/pull/2242)
> [8.14] [DOCS] Add 8.14.2 release notes (#2242)

- docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.14.3 release notes (#2245)](https://github.com/elastic/elasticsearch-hadoop/pull/2245)
> [8.15] [DOCS] Add 8.14.3 release notes (#2245)

- docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.14.3 release notes (#2245)](https://github.com/elastic/elasticsearch-hadoop/pull/2245)
> [8.14] [DOCS] Add 8.14.3 release notes (#2245)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/DependencyLicensesTask.java
- buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/info/GlobalBuildInfoPlugin.java
- dist/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- thirdparty/build.gradle
- [Update Gradle wrapper to 8.8 (#2232)](https://github.com/elastic/elasticsearch-hadoop/pull/2232)
> [7.17] Update Gradle wrapper to 8.8 (#2232)

- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- [Update Gradle wrapper to 8.9 (#2248)](https://github.com/elastic/elasticsearch-hadoop/pull/2248)
> [7.17] Update Gradle wrapper to 8.9 (#2248)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.0 release notes (#2253)](https://github.com/elastic/elasticsearch-hadoop/pull/2253)
> [8.15] [DOCS] Add 8.15.0 release notes (#2253)

- gradle/wrapper/gradle-wrapper.properties
- [Update Gradle wrapper to 8.10 (#2255)](https://github.com/elastic/elasticsearch-hadoop/pull/2255)
> [7.17] Update Gradle wrapper to 8.10 (#2255)

- gradle/wrapper/gradle-wrapper.properties
- [Update Gradle wrapper to 8.10 (#2255)](https://github.com/elastic/elasticsearch-hadoop/pull/2255)
> [8.15] Update Gradle wrapper to 8.10 (#2255)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.1 release notes (#2258)](https://github.com/elastic/elasticsearch-hadoop/pull/2258)
> [8.15] [DOCS] Add 8.15.1 release notes (#2258)

- .ci/java-versions.properties
- mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
- mr/src/test/java/org/elasticsearch/hadoop/serialization/CommandTest.java
stay in sync with minimum java version used by elasticsearch
> Update java build and runtime from 17 to 21

- gradle/wrapper/gradle-wrapper.properties
- [Update Gradle wrapper to 8.10.2 (#2267)](https://github.com/elastic/elasticsearch-hadoop/pull/2267)
> [8.x] Update Gradle wrapper to 8.10.2 (#2267)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.4 release notes (#2279)](https://github.com/elastic/elasticsearch-hadoop/pull/2279)
> [8.x] [DOCS] Add 8.15.4 release notes (#2279)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.4 release notes (#2279)](https://github.com/elastic/elasticsearch-hadoop/pull/2279)
> [8.16] [DOCS] Add 8.15.4 release notes (#2279)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.4 release notes (#2279)](https://github.com/elastic/elasticsearch-hadoop/pull/2279)
> [8.15] [DOCS] Add 8.15.4 release notes (#2279)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.0 release notes (#2283)](https://github.com/elastic/elasticsearch-hadoop/pull/2283)
> [8.x] [DOCS] Add 8.16.0 release notes (#2283)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.0 release notes (#2283)](https://github.com/elastic/elasticsearch-hadoop/pull/2283)
> [8.16] [DOCS] Add 8.16.0 release notes (#2283)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.1 release notes (#2286)](https://github.com/elastic/elasticsearch-hadoop/pull/2286)
> [8.x] [DOCS] Add 8.16.1 release notes (#2286)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.1 release notes (#2286)](https://github.com/elastic/elasticsearch-hadoop/pull/2286)
> [8.17] [DOCS] Add 8.16.1 release notes (#2286)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.1 release notes (#2286)](https://github.com/elastic/elasticsearch-hadoop/pull/2286)
> [8.16] [DOCS] Add 8.16.1 release notes (#2286)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.5.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.5 release notes (#2292)](https://github.com/elastic/elasticsearch-hadoop/pull/2292)
> [8.x] [DOCS] Add 8.15.5 release notes (#2292)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.5.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.5 release notes (#2292)](https://github.com/elastic/elasticsearch-hadoop/pull/2292)
> [8.17] [DOCS] Add 8.15.5 release notes (#2292)

- docs/src/reference/asciidoc/appendix/release-notes/8.15.5.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.15.5 release notes (#2292)](https://github.com/elastic/elasticsearch-hadoop/pull/2292)
> [8.16] [DOCS] Add 8.15.5 release notes (#2292)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.0 release notes (#2297)](https://github.com/elastic/elasticsearch-hadoop/pull/2297)
> [8.x] [DOCS] Add 8.17.0 release notes (#2297)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.0 release notes (#2297)](https://github.com/elastic/elasticsearch-hadoop/pull/2297)
> [8.17] [DOCS] Add 8.17.0 release notes (#2297)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.2 release notes (#2301)](https://github.com/elastic/elasticsearch-hadoop/pull/2301)
> [8.x] [DOCS] Add 8.16.2 release notes (#2301)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.2 release notes (#2301)](https://github.com/elastic/elasticsearch-hadoop/pull/2301)
> [8.17] [DOCS] Add 8.16.2 release notes (#2301)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.2 release notes (#2301)](https://github.com/elastic/elasticsearch-hadoop/pull/2301)
> [8.16] [DOCS] Add 8.16.2 release notes (#2301)

- .buildkite/hooks/pre-command
- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/CiUtils.groovy
- settings.gradle
This adds general support for gradle enterprise and configures CI similar to the Elasticsearch CI setup to automatically publish scans to the elastic instance.
> Add Gradle enterprise setup

- .buildkite/hooks/pre-command
- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/CiUtils.groovy
- settings.gradle
- [Add Gradle enterprise setup (#2307)](https://github.com/elastic/elasticsearch-hadoop/pull/2307)
> [8.x] Add Gradle enterprise setup (#2307)

- .buildkite/hooks/pre-command
- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/CiUtils.groovy
- settings.gradle
- [Add Gradle enterprise setup (#2307)](https://github.com/elastic/elasticsearch-hadoop/pull/2307)
> [8.16] Add Gradle enterprise setup (#2307)

- .buildkite/hooks/pre-command
- build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/CiUtils.groovy
- settings.gradle
- [Add Gradle enterprise setup (#2307)](https://github.com/elastic/elasticsearch-hadoop/pull/2307)
> [8.17] Add Gradle enterprise setup (#2307)

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/api/java/JavaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/package.scala
Apache Spark 2.x has reached end of support since 2021, we are deprecating Spark 2.x in 8.18. Support for it will be removed in 9.0. This change will be backported to 8.x branch.
> Deprecate Spark 2.x

- docs/src/reference/asciidoc/appendix/breaking.adoc
- docs/src/reference/asciidoc/core/intro/requirements.adoc
- spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/api/java/JavaEsSparkSQL.scala
- spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/package.scala
- [Deprecate Spark 2.x (#2305)](https://github.com/elastic/elasticsearch-hadoop/pull/2305)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [8.x] Deprecate Spark 2.x (#2305)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
- [Fix download url of archived hive (#2291)](https://github.com/elastic/elasticsearch-hadoop/pull/2291)
> [8.x] Fix download url of archived hive (#2291)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
- [Fix download url of archived hive (#2291)](https://github.com/elastic/elasticsearch-hadoop/pull/2291)
> [8.17] Fix download url of archived hive (#2291)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
- [Fix download url of archived hive (#2291)](https://github.com/elastic/elasticsearch-hadoop/pull/2291)
> [8.16] Fix download url of archived hive (#2291)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntFixture.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntTask.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy
- qa/kerberos/build.gradle
- [[Gradle] Remove deprecated gradle api usage (#2321)](https://github.com/elastic/elasticsearch-hadoop/pull/2321)
> [8.x] [Gradle] Remove deprecated gradle api usage (#2321)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntFixture.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntTask.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy
- qa/kerberos/build.gradle
- [[Gradle] Remove deprecated gradle api usage (#2321)](https://github.com/elastic/elasticsearch-hadoop/pull/2321)
> [8.16] [Gradle] Remove deprecated gradle api usage (#2321)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntFixture.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/buildtools/AntTask.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy
- qa/kerberos/build.gradle
- [[Gradle] Remove deprecated gradle api usage (#2321)](https://github.com/elastic/elasticsearch-hadoop/pull/2321)
> [8.17] [Gradle] Remove deprecated gradle api usage (#2321)

- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- gradle/wrapper/gradle-wrapper.properties
- qa/build.gradle
- thirdparty/build.gradle
- [Update Gradle wrapper to 8.12 (#2306)](https://github.com/elastic/elasticsearch-hadoop/pull/2306)
> [8.16] Update Gradle wrapper to 8.12 (#2306)

- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- gradle/wrapper/gradle-wrapper.properties
- qa/build.gradle
- thirdparty/build.gradle
- [Update Gradle wrapper to 8.12 (#2306)](https://github.com/elastic/elasticsearch-hadoop/pull/2306)
> [8.17] Update Gradle wrapper to 8.12 (#2306)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.3 release notes (#2329)](https://github.com/elastic/elasticsearch-hadoop/pull/2329)
> [8.16] [DOCS] Add 8.16.3 release notes (#2329)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.3 release notes (#2329)](https://github.com/elastic/elasticsearch-hadoop/pull/2329)
> [8.17] [DOCS] Add 8.16.3 release notes (#2329)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.3.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.16.3 release notes (#2329)](https://github.com/elastic/elasticsearch-hadoop/pull/2329)
> [8.x] [DOCS] Add 8.16.3 release notes (#2329)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.1 release notes (#2333)](https://github.com/elastic/elasticsearch-hadoop/pull/2333)
> [8.x] [DOCS] Add 8.17.1 release notes (#2333)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.1 release notes (#2333)](https://github.com/elastic/elasticsearch-hadoop/pull/2333)
> [8.17] [DOCS] Add 8.17.1 release notes (#2333)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [8.16] [DOCS] Add 8.16.4 release notes (#2337)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [8.17] [DOCS] Add 8.16.4 release notes (#2337)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [8.18] [DOCS] Add 8.16.4 release notes (#2337)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [8.x] [DOCS] Add 8.16.4 release notes (#2337)

- docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
> [9.0] [DOCS] Add 8.16.4 release notes (#2337)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.2 release notes (#2343)](https://github.com/elastic/elasticsearch-hadoop/pull/2343)
> [8.17] [DOCS] Add 8.17.2 release notes (#2343)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.2 release notes (#2343)](https://github.com/elastic/elasticsearch-hadoop/pull/2343)
> [8.18] [DOCS] Add 8.17.2 release notes (#2343)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.2 release notes (#2343)](https://github.com/elastic/elasticsearch-hadoop/pull/2343)
> [8.x] [DOCS] Add 8.17.2 release notes (#2343)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.2 release notes (#2343)](https://github.com/elastic/elasticsearch-hadoop/pull/2343)
> [9.0] [DOCS] Add 8.17.2 release notes (#2343)

- gradle/wrapper/gradle-wrapper.properties
- gradlew
- [Update Gradle wrapper to 8.13 (#2358)](https://github.com/elastic/elasticsearch-hadoop/pull/2358)
> [9.0] Update Gradle wrapper to 8.13 (#2358)

- gradle/wrapper/gradle-wrapper.properties
- gradlew
- [Update Gradle wrapper to 8.13 (#2358)](https://github.com/elastic/elasticsearch-hadoop/pull/2358)
> [8.x] Update Gradle wrapper to 8.13 (#2358)

- docs/reference/apache-spark-support.md
- docs/reference/hadoop-metrics.md
- docs/reference/license.md
- docs/reference/logging.md
- docs/reference/mapreduce-integration.md
Fix external links that incorrectly use `.md` instead of `.html`.
> [docs] Fix external links

- docs/reference/apache-spark-support.md
- docs/reference/hadoop-metrics.md
- docs/reference/license.md
- docs/reference/logging.md
- docs/reference/mapreduce-integration.md
- [fix external links (#2364)](https://github.com/elastic/elasticsearch-hadoop/pull/2364)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [9.0] fix external links (#2364)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.4.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.17.5.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `8.x` to `8.18`:
- [[DOCS] Add 8.17.5 release notes (#2374)](https://github.com/elastic/elasticsearch-hadoop/pull/2374)
> [8.18] [DOCS] Add 8.17.5 release notes (#2374)

- docs/release-notes/breaking-changes.md
> [DOCS] Add 9.0.0 release notes

- docs/release-notes/breaking-changes.md
- [[DOCS] Add 9.0.0 release notes (#2373)](https://github.com/elastic/elasticsearch-hadoop/pull/2373)
> [9.0] [DOCS] Add 9.0.0 release notes (#2373)

- README.md
The README file had not been updated in many years. This PR fixes broken links, removes older irrelevant information, and clarifies dependencies for Spark a little.
> Cleaning up the README field

- docs/src/reference/asciidoc/appendix/release-notes/8.17.6.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.6 release notes (#2380)](https://github.com/elastic/elasticsearch-hadoop/pull/2380)
> [8.18] [DOCS] Add 8.17.6 release notes (#2380)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.6.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `8.19` to `8.17`:
- [[DOCS] Add 8.17.6 release notes (#2380)](https://github.com/elastic/elasticsearch-hadoop/pull/2380)
> [8.17] [DOCS] Add 8.17.6 release notes (#2380)

- docs/src/reference/asciidoc/appendix/release-notes/8.18.0.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.18.1.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.18.0+1 release notes (#2383)](https://github.com/elastic/elasticsearch-hadoop/pull/2383)
> [8.18] [DOCS] Add 8.18.0+1 release notes (#2383)

- docs/src/reference/asciidoc/appendix/release-notes/8.18.2.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.18.2 release notes (#2388)](https://github.com/elastic/elasticsearch-hadoop/pull/2388)
> [8.18] [DOCS] Add 8.18.2 release notes (#2388)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.7.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.17.7 release notes (#2390)](https://github.com/elastic/elasticsearch-hadoop/pull/2390)
> [8.18] [DOCS] Add 8.17.7 release notes (#2390)

- .buildkite/dra.sh
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- hive/build.gradle
- mr/build.gradle
- spark/sql-30/build.gradle
Ensure we create an maven central publishing compliant aggregation zip for all elasticsearch hadoop files we want to publish
> [Build] Support publishing maven artifacts directly to maven central

- .buildkite/dra.sh
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- hive/build.gradle
- mr/build.gradle
- spark/sql-30/build.gradle
- [[Build] Support publishing maven artifacts directly to maven central (#2397)](https://github.com/elastic/elasticsearch-hadoop/pull/2397)
> [9.0] [Build] Support publishing maven artifacts directly to maven central (#2397)

- .buildkite/dra.sh
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- hive/build.gradle
- mr/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- [[Build] Support publishing maven artifacts directly to maven central (#2397)](https://github.com/elastic/elasticsearch-hadoop/pull/2397)
> [8.18] [Build] Support publishing maven artifacts directly to maven central (#2397)

- .buildkite/dra.sh
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- hive/build.gradle
- mr/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- [[Build] Support publishing maven artifacts directly to maven central (#2397)](https://github.com/elastic/elasticsearch-hadoop/pull/2397)
> [8.17] [Build] Support publishing maven artifacts directly to maven central (#2397)

- dist/build.gradle
- we push different tasks output into build/distribution
- should be not necessary ones we remove osshr compliant maven dra artifacts
> [Build} Ensure deterministic task execution ordering in DRA

- build.gradle
- buildSrc/build.gradle
- [Make aggregation zip compatible with release manager (#2398)](https://github.com/elastic/elasticsearch-hadoop/pull/2398)
> [9.0] Make aggregation zip compatible with release manager (#2398)

- build.gradle
- buildSrc/build.gradle
- [Make aggregation zip compatible with release manager (#2398)](https://github.com/elastic/elasticsearch-hadoop/pull/2398)
> [8.17] Make aggregation zip compatible with release manager (#2398)

- dist/build.gradle
- [Ensure deterministic task execution ordering in DRA (#2413)](https://github.com/elastic/elasticsearch-hadoop/pull/2413)
> [9.0] Ensure deterministic task execution ordering in DRA (#2413)

- dist/build.gradle
This will backport the following commits from `main` to `8.19`:
- [Ensure deterministic task execution ordering in DRA (#2413)](https://github.com/elastic/elasticsearch-hadoop/pull/2413)
> [8.19] Ensure deterministic task execution ordering in DRA (#2413)

- dist/build.gradle
- [Ensure deterministic task execution ordering in DRA (#2413)](https://github.com/elastic/elasticsearch-hadoop/pull/2413)
> [8.18] Ensure deterministic task execution ordering in DRA (#2413)

- dist/build.gradle
- [Ensure deterministic task execution ordering in DRA (#2413)](https://github.com/elastic/elasticsearch-hadoop/pull/2413)
> [8.17] Ensure deterministic task execution ordering in DRA (#2413)

- .buildkite/dra.sh
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
- dist/build.gradle
- mr/build.gradle
- spark/sql-13/build.gradle
- spark/sql-20/build.gradle
- spark/sql-30/build.gradle
- thirdparty/build.gradle
Backports #2413 #2398 & #2397 to 7.17
> [7.17] Backport maven central aggregation zip

- settings.gradle
- [Update gradle shadow plugin to 9.0.1 (#2433)](https://github.com/elastic/elasticsearch-hadoop/pull/2433)
> [9.0] Update gradle shadow plugin to 9.0.1 (#2433)

- settings.gradle
This will backport the following commits from `main` to `8.19`:
- [Update gradle shadow plugin to 9.0.1 (#2433)](https://github.com/elastic/elasticsearch-hadoop/pull/2433)
> [8.19] Update gradle shadow plugin to 9.0.1 (#2433)

- settings.gradle
- [Update gradle shadow plugin to 9.0.1 (#2433)](https://github.com/elastic/elasticsearch-hadoop/pull/2433)
> [8.18] Update gradle shadow plugin to 9.0.1 (#2433)

- docs/release-notes/index.md
This will backport the following commits from `main` to `9.1`:
- [[DOCS] Add 9.1.0 release notes (#2443)](https://github.com/elastic/elasticsearch-hadoop/pull/2443)
> [9.1] [DOCS] Add 9.1.0 release notes (#2443)

- docs/src/reference/asciidoc/appendix/release-notes/8.17.10.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.17.8.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.17.9.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
This will backport the following commits from `8.19` to `8.17`:
- [[DOCS] Add 8.17.10 release notes (#2444)](https://github.com/elastic/elasticsearch-hadoop/pull/2444)
> [8.17] [DOCS] Add 8.17.10 release notes (#2444)

- docs/src/reference/asciidoc/appendix/release-notes/8.18.3.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.18.4.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.18.5.adoc
- docs/src/reference/asciidoc/appendix/release-notes/8.18.6.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.18.6 release notes (#2448)](https://github.com/elastic/elasticsearch-hadoop/pull/2448)
> [8.18] [DOCS] Add 8.18.6 release notes (#2448)

- docs/src/reference/asciidoc/appendix/release-notes/8.18.7.adoc
- docs/src/reference/asciidoc/appendix/release.adoc
- [[DOCS] Add 8.18.7 release notes (#2452)](https://github.com/elastic/elasticsearch-hadoop/pull/2452)
> [8.18] [DOCS] Add 8.18.7 release notes (#2452)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
archives.apache.org has proven to be super slow (3h total download time lately) for dependency resolution
> Update apache archive mirror url for faster artifact resolution

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
This will backport the following commits from `main` to `8.19`:
- [Update apache archive mirror url for faster artifact resolution (#2460)](https://github.com/elastic/elasticsearch-hadoop/pull/2460)
> [8.19] Update apache archive mirror url for faster artifact resolution (#2460)

- buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/HadoopFixturePlugin.groovy
- [Update apache archive mirror url for faster artifact resolution (#2460)](https://github.com/elastic/elasticsearch-hadoop/pull/2460)
> [8.18] Update apache archive mirror url for faster artifact resolution (#2460)

- .buildkite/tests.trigger.sh
This fixes the branch selection for 9.0. without usage of quotes this would evaluate to 9 which is not a valid branch.
> Fix test trigger pipeline for 9.0 branch
