elastic/elasticsearch-hadoop

spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala

[SPARK] Handle and write null values in doWriteMap

---

docs/src/reference/asciidoc/appendix/index.adoc
docs/src/reference/asciidoc/appendix/release-notes.adoc

Incorporated release notes into the documentation. I did this manually for this release because I consolidated the 5.0.0-x release notes, but should be automated going forward.

Docs: Added release notes to appendix. Consolidated RNs for 5.0.0 GA.

---

docs/src/reference/asciidoc/index.adoc
repository-hdfs/README.md

Updating projects with respective Github repos for filing issues. Also moved es-on-yarn to the bottom and added the beta tag.

Update preface doc

---

docs/src/reference/asciidoc/core/performance.adoc

typo in performance.adoc

---

docs/src/reference/asciidoc/core/spark.adoc

wrong variable saved in java streaming example

---

spark/sql-13/src/main/scala/org/elasticsearch/spark/streaming/package.scala
spark/sql-20/src/main/scala/org/elasticsearch/spark/streaming/package.scala

Fix implicit conversion warnings

---

spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala

fixes #981
spark-sql-20 was missed when this was first added

add scaled and half float to schemautils (#981)

---

mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/AbstractBulkFactory.java

Added support for handling Date and Timestamp objects - convert to epoch milliseconds
This addresses #931 

Support Date / Timestamp objects

---

dist.gradle
docs/src/reference/asciidoc/appendix/release-notes/5.4.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc
docs/src/reference/asciidoc/yarn/index.adoc
yarn/README.md

This PR adds deprecation messages for YARN to the project README and to the official documentation.

Deprecate YARN Support in 5.5

---

build.gradle
spark/core/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
spark/core/main/scala/org/elasticsearch/spark/rdd/EsSpark.scala

This pull request is a last step of #974 which fixes #970.

Fix remaining Scala warnings (#970)

---

build.gradle
spark/core/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDD.scala
spark/core/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDDIterator.scala
spark/core/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
spark/core/main/scala/org/elasticsearch/spark/rdd/JavaEsRDD.scala
spark/core/main/scala/org/elasticsearch/spark/rdd/ScalaEsRDD.scala
spark/core/main/scala/org/elasticsearch/spark/serialization/ReflectionUtils.scala
spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowRDD.scala
spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/ScalaEsRowRDD.scala

Add -Xfatal-warnings option to scalac and fix all warnings

---

mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java

Hi,
I recently encountered a connection leak when using the elasticsearch-hadoop Spark Streaming support. After profiling the application, I found the connection leak is related to the WAN support. The details are listed below.
This is a simple `saveToEs` application as follows.
```scala
object StreamingSample {
def main(args: Array[String]): Unit = {
val conf = new SparkConf().setAppName("sample streaming")
val ssc = new StreamingContext(conf, Seconds(5))
val rdd = ssc.sparkContext.makeRDD(Seq[Map[String, Int]]())
new ConstantInputDStream(ssc, rdd).saveToEs {
Map(
ES_NODES    -> "localhost",
ES_RESOURCE -> "demo/job",
ES_NODES_WAN_ONLY -> "true"
)
}
ssc.start
ssc.awaitTermination
}
}
```
- Spark 2.2.0
- Elasticsearch 5.5.2
- OpenJDK Runtime Environment 1.8.0_131
Under the top-level Spark …

Connection leak that occurs when using the WAN support

---

docs/src/reference/asciidoc/core/spark.adoc

Add pushdown filters table for es-spark documentation

---

docs/src/reference/asciidoc/core/spark.adoc

Fix copy/paste

---

docs/src/reference/asciidoc/core/index.adoc
docs/src/reference/asciidoc/core/kerberos.adoc
docs/src/reference/asciidoc/index.adoc

This PR adds documentation for the new Kerberos authentication features in ES-Hadoop.

Add documentation for Kerberos Authentication mode

---

docs/src/reference/asciidoc/appendix/breaking.adoc

Backports https://github.com/elastic/elasticsearch-hadoop/pull/1271

[DOCS] Adds tagged region for notable breaking changes

---

mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java

When initiating a scroll in 5.x and above, an empty initial response indicates that the scroll/slice being read has no data in it. When ES-Hadoop reads this initial empty response it assumes that the scroll is empty and concludes the read operation. In ES 2.x however, the initial scroll response is always empty, and the resulting behavior is that ES-Hadoop reads nothing from the index at all. This PR adds in a switch when reading from ES 2.x and below that if the initial scroll request is empty or marked as concluded, it is modified to allow for subsequent requests to determine if it is actually empty or not.

Fix incorrect scroll termination for ES 2.x

---

README.md
buildSrc/esh-version.properties

docs PR : https://github.com/elastic/elasticsearch-hadoop/pull/1305

version bump to 6.8.2

---

README.md
buildSrc/esh-version.properties
docs/src/reference/asciidoc/index.adoc

version bump to 7.2.1

---

docs/src/reference/asciidoc/index.adoc

This PR updates the version information from 7.3.0 to 7.4.0 in the 7.x branch.

[DOCS] Updates documentation version

---

README.md
buildSrc/esh-version.properties
docs/src/reference/asciidoc/index.adoc

_Do not merge until green light given to bump versions (CI failures are expected)_

bump verstion 6.8.2 -> 6.8.3

---

README.md
buildSrc/esh-version.properties
docs/src/reference/asciidoc/index.adoc

_Do not merge until green light for merge_

bump version 7.2.1->7.2.2

---

spark/sql-20/src/main/scala/org/elasticsearch/spark/deploy/yarn/security/EsServiceCredentialProvider.scala

Cloudera's CDS 2.2.0+ Spark fork introduced a non-passive method
signature that results in the inability for the ES hadoop integration
to work.  Cloudera's CDS fork is the main means for CDH5 consumers to
consume newer versions of Spark. CDS is only availble to be installed
via a Cloudera Manager's parcel and is distinctly different from the (elder)
version of Apache Spark that ships with CDH5. Supporting this fork is
challenging since it difficult to test manually, and even more
so with the integration tests. CDS is for CDH5 consumers (likely the majority
at this time) that want to use Java 8 (likey the majority at this time),
and run newer versions of Spark (a very popular integration).
Related commit: https://github.com/cloudera/spark/commit/0972663ef3a87f4dcf2f4a936216bb5da0232b4e#diff …

Fix for Cloudera CDS 2.2.0+ Spark credentialsRequired method

---

docs/src/reference/asciidoc/appendix/release-notes/7.3.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adds release notes for 7.3.1.
I'll remove the comment and update the date in `7.3.1.adoc` on release day.
**DO NOT MERGE UNTIL RELEASE DAY**

[DOCS] Add 7.3.1 release notes

---

README.md
buildSrc/esh-version.properties
docs/src/reference/asciidoc/index.adoc

version bump for 7x to 7.5

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

6.8.3 Release Notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.4.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adds 7.4.0 release notes.
Will update placeholder date and merge on release day.

[DOCS] Add 7.4.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adds release notes for the 6.8.4 release. Will update the date placeholder on the day of release.

[DOCS] Add 6.8.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.4.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adds release notes for the 7.4.1 release. Will update the date placeholder on the day of release.

[DOCS] Add 7.4.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.4.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

This reverts commit 6cbb84c2e27f7b6ae897ac239bba4639f9f7e191.

Revert "[DOCS] Add 7.4.1 release notes (#1372)"

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

This reverts commit 2e602b357ccac1402d0243c03f8c18f31ee07b0e.

Revert "[DOCS] Add 6.8.4 release notes (#1373)"

---

README.md
buildSrc/esh-version.properties

Version bump to 6.8.5

---

README.md
buildSrc/esh-version.properties

Bump version to 7.4.2

---

README.md

Update stable version in readme

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.5.adoc
docs/src/reference/asciidoc/appendix/release.adoc

*DO NOT MERGE UNTIL RELEASE DAY.*
Adds release notes for 6.8.5. Will update date placeholder on day of release.

[DOCS] Add 6.8.5 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.5.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

*DO NOT MERGE UNTIL RELEASE DAY.*
Adds release notes for 7.5.0. Will update date placeholder on day of release.

[DOCS] Add 7.5.0 release notes

---

docs/src/reference/asciidoc/page_header.html

Relates to: https://github.com/elastic/docs/pull/1426

[DOCS] Add EOL notice.

---

docs/src/reference/asciidoc/appendix/release-notes/7.5.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adds release notes for the 7.5.1 release.

[DOCS] Add 7.5.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.6.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 6.8.6 release notes

---

README.md
buildSrc/esh-version.properties

Apologies, again, for my editor changing a bunch of whitespace :(  I need to just switch to a different editor when assembling these PRs.

Bump version to 7.7

---

docs/src/reference/asciidoc/appendix/release-notes/7.5.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

This PR adds a placeholder for the release notes.

[DOCS] Adds placeholder for release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.6.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.6.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.6.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.6.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.7.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 6.8.7 release notes

---

README.md
buildSrc/esh-version.properties

_hold merging till ready for release_

bump version to 6.8.8

---

README.md
buildSrc/esh-version.properties

**_Do not merge until 7.7 has been branched out._**
Bump 7.x to 7.8.0

Bump 7.x to 7.8.0

---

README.md
buildSrc/esh-version.properties

_DO NOT MERGE UNTIL 6.8.8 IS RELEASED_

bump version to 6.8.9

---

README.md
buildSrc/esh-version.properties

Bump 7.x to 7.9.0 as part of the 7.8 release.

Bump 7.x to 7.9.0

---

README.md

**_Do not merge until 7.7.0 is being released._**
Update README references to latest stable, 7.7.0

Update references to latest stable, 7.7.0

---

README.md
buildSrc/esh-version.properties

**DO NOT MERGE UNTIL PAST 7.7 RELEASE.**
Bump 7.7 to 7.7.1

Bump 7.7 to 7.7.1

---

docs/src/reference/asciidoc/appendix/release-notes/7.7.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.7.1 release notes (#1479)

---

docs/src/reference/asciidoc/appendix/release-notes/7.7.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.8] [DOCS] Add 7.7.1 release notes (#1479)

---

docs/src/reference/asciidoc/appendix/release-notes/7.7.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.7] [DOCS] Add 7.7.1 release notes (#1479)

---

README.md
buildSrc/esh-version.properties

Must be merged after https://github.com/elastic/elasticsearch/pull/57599

Bump version to 6.8.11

---

docs/src/reference/asciidoc/appendix/release-notes/7.8.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.8.0 release notes (#1488)

---

docs/src/reference/asciidoc/appendix/release-notes/7.8.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.8] [DOCS] Add 7.8.0 release notes (#1488)

---

docs/src/reference/asciidoc/appendix/release-notes/7.8.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.8.1 release notes (#1500)

---

docs/src/reference/asciidoc/appendix/release-notes/7.8.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.9] [DOCS] Add 7.8.1 release notes (#1500)

---

docs/src/reference/asciidoc/appendix/release-notes/7.8.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.8] [DOCS] Add 7.8.1 release notes (#1500)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.9.0 release notes (#1515)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.9] [DOCS] Add 7.9.0 release notes (#1515)

---

README.md
buildSrc/esh-version.properties

Relates elastic/elasticsearch#61197

Bump version to 6.8.13

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.9.1 release notes (#1518)

[7.x] [DOCS] Add 7.9.1 release notes (#1518)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.9.2 release notes (#1526)

[master] [DOCS] Add 7.9.2 release notes (#1526)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.9.2 release notes (#1526)

[7.x] [DOCS] Add 7.9.2 release notes (#1526)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.9.3 release notes (#1545)

[7.x] [DOCS] Add 7.9.3 release notes (#1545)

---

docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Backports the following commits to 7.10:
- [DOCS] Add 7.9.3 release notes (#1545)

[7.10] [DOCS] Add 7.9.3 release notes (#1545)

---

README.md
buildSrc/esh-version.properties

bump the version to 6.8.14

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Backports the following commits to 7.10:
- [DOCS] Add 7.10.0 release notes (#1553)

[7.10] [DOCS] Add 7.10.0 release notes (#1553)

---

README.md
buildSrc/esh-version.properties

***Do not merge until 7.10.0 is being released***

Bump 7.10.0 to 7.10.1

---

README.md

***Do not merge until 7.10.0 is being released***
Update the references to the current stable release to point to 7.10.0

Update references to latest stable, 7.10.0

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[master] [DOCS] Add 7.10.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.10.1 release notes (#1560)

[7.x] [DOCS] Add 7.10.1 release notes (#1560)

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Backports the following commits to 7.10:
- [DOCS] Add 7.10.1 release notes (#1560)

[7.10] [DOCS] Add 7.10.1 release notes (#1560)

---

README.md
buildSrc/esh-version.properties

Bump version for 7.10.1 release

---

docs/src/reference/asciidoc/core/metrics.adoc
docs/src/reference/asciidoc/index.adoc

Fixes several broken links to the Hadoop docs.

[DOCS] Fix links to Hadoop docs

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.10.2 release notes (#1568)

[master] [DOCS] Add 7.10.2 release notes (#1568)

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.11.0 release notes (#1569)

[master] [DOCS] Add 7.11.0 release notes (#1569)

---

docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc

DO NOT MERGE UNTIL AFTER RELEASE.

[DOCS] Remove 7.10.2 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.14.adoc

DO NOT MERGE UNTIL AFTER RELEASE.

[DOCS] Remove 6.8.14 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc

[DOCS] Remove 7.11.0 coming tag

---

README.md
buildSrc/esh-version.properties

Bump version to 6.8.15

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.11.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.11.1 release notes (#1602)

[master] [DOCS] Add 7.11.1 release notes (#1602)

---

mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java

- New Data Tiers role support (#1613)

[7.x] New Data Tiers role support (#1613)

---

mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java

Backports the following commits to 7.12:
- New Data Tiers role support (#1613)

[7.12] New Data Tiers role support (#1613)

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.11.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.11.2 release notes (#1611)

[master] [DOCS] Add 7.11.2 release notes (#1611)

---

docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.11.2 release notes (#1611)

[7.x] [DOCS] Add 7.11.2 release notes (#1611)

---

docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.12.0 release notes (#1610)

[master] [DOCS] Add 7.12.0 release notes (#1610)

---

README.md
buildSrc/esh-version.properties

Bumping versions for 7.12 on the 7.12 branch.

Version bumps for 7.12 release

---

docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.12.1 release notes (#1645)

[master] [DOCS] Add 7.12.1 release notes (#1645)

---

docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc

[DOCS] Remove 7.12.1 coming tag

---

README.md
buildSrc/esh-version.properties

This PR executes the version bump for the 7.12.2 release.

Bump version for 7.12.2

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.0 release notes (#1662)

[master] [DOCS] Add 7.13.0 release notes (#1662)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc

[DOCS] Remove 7.13.0 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.16.adoc

[DOCS] Remove 6.8.16 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.1 release notes (#1673)

[master] [DOCS] Add 7.13.1 release notes (#1673)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.1 release notes (#1673)

[7.x] [DOCS] Add 7.13.1 release notes (#1673)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc

[DOCS] Remove 7.13.1 coming tag

---

README.md
buildSrc/esh-version.properties

Bump version to 7.13.2 after the release of v7.13.1

Bump version to 7.13.2

---

buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy

Remove usages of the conjars repository as it is being sunset.

Remove the conjars repository from the build

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.2 release notes (#1687)

[7.x] [DOCS] Add 7.13.2 release notes (#1687)

---

spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala

Backports the following commits to 7.13:
- Fix failing strict wildcard pushdown tests (#1683)

[7.13] Fix failing strict wildcard pushdown tests (#1683)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc

[DOCS] Remove 7.13.2 coming tag

---

README.md
buildSrc/esh-version.properties

Bump 7.x branch to 7.15

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.4 release notes (#1717)

[master] [DOCS] Add 7.13.4 release notes (#1717)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 7.13.4 release notes (#1717)

[7.x] [DOCS] Add 7.13.4 release notes (#1717)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Backports the following commits to 7.14:
- [DOCS] Add 7.13.4 release notes (#1717)

[7.14] [DOCS] Add 7.13.4 release notes (#1717)

---

docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc

[DOCS] Remove 7.13.4 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.18.adoc

[DOCS] Remove 6.8.18 coming tag

---

buildSrc/esh-version.properties

Fix the development version number for ES-Hadoop to be in line with the expected stack version for development.

Update the development version of ES-Hadoop

---

README.md
buildSrc/esh-version.properties

Bump version to 7.16.0

---

docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Backports the following commits to 7.15:
- [DOCS] Add 7.14.1 release notes (#1740)

[7.15] [DOCS] Add 7.14.1 release notes (#1740)

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha2.adoc

[DOCS] Remove coming tag from 8.0.0-alpha2 RNs

---

docs/src/reference/asciidoc/appendix/release-notes/7.14.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.14.2 release notes (#1757)

---

docs/src/reference/asciidoc/appendix/release-notes/7.14.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.15] [DOCS] Add 7.14.2 release notes (#1757)

---

docs/src/reference/asciidoc/appendix/release-notes/7.15.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.x] [DOCS] Add 7.15.0 release notes (#1767)

---

docs/src/reference/asciidoc/appendix/release-notes/7.15.1.adoc

[7.x] [DOCS] Remove 7.15.1 tag

---

spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala

Stored script request body has changed in 8.0. Updating test code to reflect this change.

Fix script update tests in Spark

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc

[DOCS] Remove coming tag from 8.0.0-beta1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc

[8.x] [DOCS] Remove coming tag from 8.0.0-beta1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.15.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[7.16] [DOCS] Add 7.15.2 release notes (#1804)

---

spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala

Fixing a scala compilation problem that happened with certain scala compilers.

Fixing a scala compilation problem (#1855)

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc

[DOCS] Remove 8.0.0-rc1 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc

- [DOCS] Add missing items to 8.0.0-rc1 release notes (#1863)

[master] [DOCS] Add missing items to 8.0.0-rc1 release notes (#1863)

---

docs/src/reference/asciidoc/appendix/release-notes/6.8.23.adoc

[DOCS] Remove coming tag from 6.8.23 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc

[DOCS] Remove coming tag from 7.16.3 release notes

---

README.md
buildSrc/esh-version.properties

Bump version to 6.8.24

---

README.md
buildSrc/esh-version.properties

Bump version to 7.16.4

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc

[DOCS] Remove 8.0.0-rc2 coming tag

---

docs/src/reference/asciidoc/appendix/breaking.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.0.0.adoc

[DOCS] Remove 8.0.0 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1910.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/current/eshadoop-8.0.1.html

[DOCS] Add 8.0.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 8.0.1 release notes (#1910)

[master] [DOCS] Add 8.0.1 release notes (#1910)

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.1.adoc

[DOCS] Remove 7.17.1 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/8.0.1.adoc

[DOCS] Remove 8.0.1 coming tag

---

docs/src/reference/asciidoc/appendix/release-notes/8.1.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1930.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/8.1/eshadoop-8.1.1.html

[DOCS] Add 8.1.1 release notes

---

qa/kerberos/build.gradle
qa/kerberos/src/itest/java/org/elasticsearch/hadoop/qa/kerberos/AbstractClusterVerificationTests.java
qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/LoadToES.scala
qa/kerberos/src/main/scala/org/elasticsearch/hadoop/qa/kerberos/spark/ReadFromES.scala
spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala

[8.1] Set UserProvider before discovery in Spark SQL integrations (#1934)

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Adds 7.17.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.1.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.1.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1952.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.3.html

[DOCS] Add 7.17.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1951.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.1.3.html

[DOCS] Add 8.1.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

- [DOCS] Add 8.1.3 release notes (#1951)

[8.1] [DOCS] Add 8.1.3 release notes (#1951)

---

docs/src/reference/asciidoc/appendix/release-notes/8.2.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1956.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.2.0.html

[DOCS] Add 8.2.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1961.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.4.html

[DOCS] Add 7.17.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.2.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1960.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.2.1.html

[DOCS] Add 8.2.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.3.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1972.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.3.0.html

[DOCS] Add 8.3.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.3.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1975.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.3.1.html

[DOCS] Add 8.3.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.3.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1983.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.3.3.html

[DOCS] Add 8.3.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.4.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1989.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.4.0.html

[DOCS] Add 8.4.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.6.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1991.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.6.html

[DOCS] Add 7.17.6 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.4.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_1998.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.4.2.html

[DOCS] Add 8.4.2 release notes

---

docs/src/reference/asciidoc/index.adoc

[8.4] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[8.2] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[8.5] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[8.1] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[8.0] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.17] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.16] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.15] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.13] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.12] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.11] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.10] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.9] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.8] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.7] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.6] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.5] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.4] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.3] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.2] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.1] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[7.0] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/index.adoc

[6.8] Update index.adoc (#2000)

---

docs/src/reference/asciidoc/appendix/release-notes/8.5.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.5.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.7.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2033.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.7.html

[DOCS] Add 7.17.7 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.5.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2040.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.5.1.html

[DOCS] Add 8.5.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.5.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2042.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/main/eshadoop-8.5.2.html

[DOCS] Add 8.5.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.5.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2045.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/main/eshadoop-8.5.3.html

[DOCS] Add 8.5.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.8.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2046.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.8.html

[DOCS] Add 7.17.8 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.6.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2053.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.6.0.html

[DOCS] Add 8.6.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.6.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2059.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.6.1.html

[DOCS] Add 8.6.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.9.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2063.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.9.html

[DOCS] Add 7.17.9 release notes

---

build.gradle
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/ConcatFilesTask.java
dist/build.gradle

- Fix dependency info generation on the way

Fix DRA build by removing Gradle 8 deprecation warnings

---

docs/src/reference/asciidoc/appendix/release-notes/8.7.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2073.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.7.0.html

[DOCS] Add 8.7.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.7.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[8.7] [DOCS] Add 8.7.0 release notes (#2073)

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.10.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2085.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.10.html

[DOCS] Add 7.17.10 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.7.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2084.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.7.1.html

[DOCS] Add 8.7.1 release notes

---

build.gradle
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/ConcatFilesTask.java
dist/build.gradle

Fix dependency info generation on the way

[8.7] Fix DRA build by removing Gradle 8 deprecation warnings #2071

---

docs/src/reference/asciidoc/appendix/release-notes/8.8.1.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.8.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2103.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.8.2.html

[DOCS] Add 8.2.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.11.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2104.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.11.html

[DOCS] Add 7.17.11 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.12.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2111.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.12.html

[DOCS] Add 7.17.12 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.9.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2122.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.9.1.html

[DOCS] Add 8.9.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.10.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.10.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.10.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.10.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.10.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.10.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.14.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2145.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.14.html

[DOCS] Add 7.17.14 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.10.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.10.3 release notes (#2142)

---

docs/src/reference/asciidoc/appendix/release-notes/8.10.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] 8.10.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.11.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2154.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.11.0.html

[DOCS] Add 8.11.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.15.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2161.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.15.html

[DOCS] Add 7.17.15 release notes

---

buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/DfsCopy.groovy
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HadoopMRJob.groovy
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/HiveBeeline.groovy
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/tasks/SparkApp.groovy

TestClusterAware API has changed in the elasticsearch build tools.

Fix incompatibility to TestClusterAware api change

---

gradle/wrapper/gradle-wrapper.properties

Keep build up-to-date and gradle version in sync with version used in ES build

Update gradle wrapper to 8.5

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.16.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2184.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.16.html

[DOCS] Add 7.17.16 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2183.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.11.3.html

[DOCS] Add 8.11.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.11.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2189.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.11.4.html

[DOCS] Add 8.11.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.12.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2192.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.12.0.html

[DOCS] Add 8.12.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.17.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2194.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.17.html

[DOCS] Add 7.17.17 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.18.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2196.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.18.html

[DOCS] Add 7.17.18 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.12.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2202.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.12.2.html

[DOCS] Add 8.12.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.13.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2205.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.13.0.html

[DOCS] Add 8.13.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.13.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2211.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.13.1.html

[DOCS] Add 8.13.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.20.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2219.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.20.html

[DOCS] Add 7.17.20 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.13.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2218.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.13.2.html

[DOCS] Add 8.13.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.13.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2223.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.13.3.html

[DOCS] Add 8.13.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.21.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2224.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.21.html

[DOCS] Add 7.17.21 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.13.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2226.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.13.4.html

[DOCS] Add 8.13.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.14.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2233.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.14.0.html

[DOCS] Add 8.14.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.22.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2238.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.22.html

[DOCS] Add 7.17.22 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.14.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2239.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.14.1.html

[DOCS] Add 8.14.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.14.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2242.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.14.2.html

[DOCS] Add 8.14.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2245.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.14.3.html

[DOCS] Add 8.14.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2253.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.15.0.html

[DOCS] Add 8.15.0 release notes

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle wrapper to 8.10

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.1

[DOCS] Add 8.15.1 release notes

---

README.md
buildSrc/esh-version.properties

Bumps the version to 9.0.0 to prepare for next major stack version release.

Bump version to 9.0.0

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.23.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2262.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.23.html

[DOCS] Add 7.17.23 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.24.adoc
docs/src/reference/asciidoc/appendix/release.adoc

https://elasticsearch-hadoop_2263.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.17.24.html

[DOCS] Add 7.17.24 release notes

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle wrapper to 8.10.2

Update Gradle wrapper to 8.10.2

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.3

[DOCS] Add 8.15.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.3

[DOCS] Add 8.15.3 release notes (#2271)

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.25.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.17.25 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.4

[DOCS] Add 8.15.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.0

[DOCS] Add 8.16.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.1

[DOCS] Add 8.16.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.15.5.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.5

[DOCS] Add 8.15.5 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.15.5

[DOCS] Add 8.17.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.26.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 7.17.26

[DOCS] Add 7.17.26 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.2

[DOCS] Add 8.16.2 release notes

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
gradle/wrapper/gradle-wrapper.properties
qa/build.gradle
thirdparty/build.gradle

Update Gradle wrapper to 8.12

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.27.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 7.17.27 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.3

[DOCS] Add 8.16.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.17.1

[DOCS] Add 8.17.1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.4

[DOCS] Add 8.16.4 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.17.2

[DOCS] Add 8.17.2 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.5.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.4

[DOCS] Add 8.16.5 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.16.5.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.16.4

[DOCS] Add 8.16.5 release notes (#2351)

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.17.3

[DOCS] Add 8.17.3 release notes (#2355)

---

.buildkite/dra-workflow.trigger.sh

Skip DRA staging builds for 9.0.0 for now

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.4.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.17.5.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.17.5
Adding missing release notes for 8.17.4

[DOCS] Add 8.17.5 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.18.0.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.18.1.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.18.0 and 8.18.1

[DOCS] Add 8.18.0+1 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.18.2.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.18.2

[DOCS] Add 8.18.2 release notes

---

build.gradle
buildSrc/build.gradle

- Update nmcp version on the way
- fix typo
- use unique name and compatible folder for zip

Make aggregation zip compatible with release manager

---

dist/build.gradle
hive/build.gradle
pig/build.gradle
spark/sql-13/build.gradle
spark/sql-20/build.gradle

fix broken dra publishing of existing maven artifacts

[7.17] Fix backwards compatibility with existing dra maven artifacts

---

mr/build.gradle
spark/sql-13/build.gradle
spark/sql-20/build.gradle
storm/build.gradle

Add more missing DRAs and fix typo

[7.17] Another try fixing DRA on 7.17

---

docs/release-notes/index.md

Adds historical release notes for Hadoop 9.1.0

[DOCS] Add 9.1.0 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.17.10.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.17.8.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.17.9.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Adding release notes for 8.17.8, 8.17.9, and 8.17.10

[DOCS] Add 8.17.10 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.19.0.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.19.1.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.19.2.adoc
docs/src/reference/asciidoc/appendix/release-notes/8.19.3.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Add release notes for 8.19.0, 8.19.1, 8.19.2, and 8.19.3

[DOCS] Add 8.19.3 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/7.17.28.adoc
docs/src/reference/asciidoc/appendix/release-notes/7.17.29.adoc
docs/src/reference/asciidoc/appendix/release.adoc

Add release notes for 7.17.28 and 7.17.29

[DOCS] Add 7.17.29 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.18.7.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.18.7 release notes

---

docs/src/reference/asciidoc/appendix/release-notes/8.19.4.adoc
docs/src/reference/asciidoc/appendix/release.adoc

[DOCS] Add 8.19.4 release notes
